F&GDEV/src/objects/Approval_State__c.object
<CustomObject>
    <fields>
        <fullName>Policy_Form__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Policy Form</label>
        <referenceTo>Policy_Form_Detail__c</referenceTo>
        <relationshipName>Approval_States</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Situs_State__c</fullName>
        <label>Situs_State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>NE</fullName>
                </value>
                <value>
                    <fullName>NV</fullName>
                </value>
                <value>
                    <fullName>NH</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Approved Situs State</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Approval State Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approved Situs States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

F&GDEV/src/objects/Policy_Form_Detail__c.object
<CustomObject>
    <description>Object utilized for Product Development efforts</description>
    <fields>
        <fullName>Insurance_Type__c</fullName>
        <label>Insurance Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Annuity</fullName>
                </value>
                <value>
                    <fullName>Life</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Policy Form</label>
    <nameField>
        <label>Policy Form</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Forms</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

F&GDEV/src/classes/DAL_Approval_State_T.cls
@isTest
public class DAL_Approval_State_T {
    
    public static User admin_User;
    public static Integer count =1;
    public static string SYSTEM_ADMINISTRATOR_PROFILE ='System Administrator';
    public static List<Policy_Form_Detail__c> policyForms = new List<Policy_Form_Detail__c>();
    public static List<Approval_State__c> approvalStates = new List<Approval_State__c>();
    
    static void testData()
    {
        admin_User = TestDataFactory.createUser(true,true,SYSTEM_ADMINISTRATOR_PROFILE);
        System.runAs(admin_User)
        {
            Map<String,Object> policyFormDetailsMap = new Map<String,Object>();
            policyFormDetailsMap.put('Insurance_Type__c','Life');
        	for(Integer i = 0 ; i<count; i++)
            {
                policyForms.add((Policy_Form_Detail__c) TestDataFactory.operationOnObjectRecord(null, 'Policy_Form_Detail__c', policyFormDetailsMap));
            }
            insert policyForms;
            
            Map<String,Object> approvalStatesMap = new Map<String,Object>();
            approvalStatesMap.put('Policy_Form__c',policyForms[0].Id);
            approvalStatesMap.put('Situs_State__c','AK');
            for(Integer i = 0 ; i<count+1; i++)
            {
                approvalStates.add((Approval_State__c) TestDataFactory.operationOnObjectRecord(null, 'Approval_State__c', approvalStatesMap));
            }
            insert approvalStates;
        }
    }
    static testmethod void testDALMethods()
    {
        testData();
        Set<Id> setPolicyFormId = new Set<Id>();
        for(Policy_Form_Detail__c policyForm : policyForms)
        {
            setPolicyFormId.add(policyForm.Id);
        }
        test.startTest();
        List<Approval_State__c> lstApprovalStates = DAL_Approval_State.getPrimaryApprovalStateByParentIds(setPolicyFormId);
        lstApprovalStates = new List<Approval_State__c>();
        lstApprovalStates = DAL_Approval_State.getApprovalStateByParentIds(setPolicyFormId);
        System.assertEquals(count+1, lstApprovalStates.size());
        test.stopTest();
        
    }
}