F&GDEV/src/objects/Approval_State__c.object
<CustomObject>
    <fields>
        <fullName>Policy_Form__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Policy Form</label>
        <referenceTo>Policy_Form_Detail__c</referenceTo>
        <relationshipName>Approval_States</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Situs_State__c</fullName>
        <label>Situs_State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>NE</fullName>
                </value>
                <value>
                    <fullName>NV</fullName>
                </value>
                <value>
                    <fullName>NH</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Approved Situs State</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Approval State Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approved Situs States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

F&GDEV/src/objects/Filing_Status__c.object
<CustomObject>
    <description>Object utilized for Product Development efforts</description>
    <fields>
        <fullName>Filing_Status__c</fullName>
        <label>Filing Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Pending Act Support</fullName>
                </value>
                <value>
                    <fullName>Filed</fullName>
                </value>
                <value>
                    <fullName>Objection</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Not Filing</fullName>
                </value>
                <value>
                    <fullName>Pending Compact</fullName>
                </value>
                <value>
                    <fullName>Pending Group</fullName>
                </value>
                <value>
                    <fullName>Approved - Dependent Group</fullName>
                </value>
                <value>
                    <fullName>Approved - Compact</fullName>
                </value>
                <value>
                    <fullName>Approved - Exempt</fullName>
                </value>
                <value>
                    <fullName>Approved - Dependent Compact</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Filed with DOI</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Targeted</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Filing_Strategy__c</fullName>
        <label>Filing Strategy</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Individual Filing</fullName>
                </value>
                <value>
                    <fullName>Compact Filing</fullName>
                </value>
                <value>
                    <fullName>Compact Dependent</fullName>
                </value>
                <value>
                    <fullName>Group Filing</fullName>
                </value>
                <value>
                    <fullName>Group Dependent</fullName>
                </value>
                <value>
                    <fullName>Exempt</fullName>
                </value>
                <value>
                    <fullName>File &amp; Use</fullName>
                </value>
                <value>
                    <fullName>Not Filing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Policy_Form__c</fullName>
        <label>Policy Form</label>
        <referenceTo>Policy_Form_Detail__c</referenceTo>
        <relationshipLabel>Policy Form States</relationshipLabel>
        <relationshipName>Filing_Statuses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Situs_State__c</fullName>
        <inlineHelpText>What is the situs/compact state for the dependency?</inlineHelpText>
        <label>Situs/Compact State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>NE</fullName>
                </value>
                <value>
                    <fullName>NV</fullName>
                </value>
                <value>
                    <fullName>NH</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>State_Approval_Date__c</fullName>
        <inlineHelpText>This should be completed if Exempt or Approved.</inlineHelpText>
        <label>State Approval Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Submitted_to_State_Date__c</fullName>
        <label>Submitted to State Date</label>
        <type>Date</type>
    </fields>
    <label>Policy Form State</label>
    <nameField>
        <label>Policy Form State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Form States</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

F&GDEV/src/objects/Policy_Form_Detail__c.object
<CustomObject>
    <description>Object utilized for Product Development efforts</description>
    <fields>
        <fullName>Filing_Strategy__c</fullName>
        <label>Filing Strategy</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Individual</fullName>
                </value>
                <value>
                    <fullName>IIPRC</fullName>
                </value>
                <value>
                    <fullName>Group</fullName>
                </value>
                <value>
                    <fullName>TBD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Policy Form</label>
    <nameField>
        <label>Policy Form</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Forms</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

F&GDEV/src/objects/Product_State_Status__c.object
<CustomObject>
    <description>Value set via trigger, to match the filing status on the related Policy Form State record, so that it can be used in a roll-up summary field on the Product State record.</description>
    <fields>
        <fullName>Filing_Status__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Policy Form State</label>
        <referenceTo>Filing_Status__c</referenceTo>
        <relationshipLabel>Product State Policy Form Associations</relationshipLabel>
        <relationshipName>Product_State_Statuses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product State Policy Form Association</label>
    <nameField>
        <displayFormat>PSPF - {0000}</displayFormat>
        <label>Product State Policy Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product State Policy Form Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

F&GDEV/src/classes/PolicyStateHandler.cls
public with sharing class PolicyStateHandler extends BaseTriggerHandler {
	
	
	private List<Filing_Status__c> newFilingStatus;
    private List<Filing_Status__c> oldFilingStatuss;
    private Map<ID, Filing_Status__c> newFilingStatusMap;
    private Map<ID, Filing_Status__c> oldFilingStatuslMap;
	
	public PolicyStateHandler()
    {
        oldFilingStatuss = (List<Filing_Status__c>)Trigger.old;
        newFilingStatus = (List<Filing_Status__c>)Trigger.new;
        newFilingStatusMap = (Map<ID, Filing_Status__c>)Trigger.newMap;
        oldFilingStatuslMap = (Map<ID, Filing_Status__c>)Trigger.oldMap;
    }
    
    
     @TestVisible
    protected override void beforeInsert()
    {
    	if(TriggerCheck.canRun('TH_POLICYSTATEHANDLER'))
        {
    		namePolicyStateRecord(Trigger.isBefore, Trigger.isInsert, newFilingStatus);
        }
    }
    
    @TestVisible
    protected override void afterUpdate()
    {
		if(TriggerCheck.canRun('TH_POLICYSTATEHANDLER'))
		{
			policyStateStatusChange(Trigger.isAfter, Trigger.isUpdate, oldFilingStatuslMap, newFilingStatusMap);
			//
			setApprovalDateOnPoilcyForm(oldFilingStatuslMap, newFilingStatusMap);
		}
    }
    
    // Requirement to Functionality to update dependent filings when the situs state or compact record is approved
   public void setApprovalDateOnPoilcyForm(Map<Id, Filing_Status__c> oldMap, Map<Id, Filing_Status__c> newMap)
   {
   	   Set<Id> setPolicyFormAffected = new Set<Id>();
   	   Map<Id,Filing_Status__c> mapGroupFilingPolicyFormDateTime = new Map<Id,Filing_Status__c>();
   	   Map<Id,Filing_Status__c> mapCompactFilingPolicyFormDateTime = new Map<Id,Filing_Status__c>();
   	   List<Filing_Status__c> lstFilingStatusToUpdate = new List<Filing_Status__c>();
   	   for(Filing_Status__c policyState : newMap.values()) 
   	   {
   	    	system.debug(' policyState.State_Approval_Date__c::::'+ policyState.Submitted_to_State_Date__c);
   	    	
   	    	if(policyState.Submitted_to_State_Date__c == null)
   	       {
	   	    	if(  policyState.State_Approval_Date__c == null &&
	   	    		(policyState.Filing_Strategy__c == 'Group Filing' 
	   	    		 || policyState.Filing_Strategy__c == 'Compact Filing'))
	   	    	{
	   	    		Trigger.new[0].addError('Approval date is required for Group filing and Compact filing ');
   	    	}
   	       }
   	   }
   	   
   	   
   	   for(Filing_Status__c policyState : newMap.values()) 
   	   {
   	       if( policyState.State_Approval_Date__c != null 
   	       	 && policyState.Filing_Strategy__c != null
   	       	 && policyState.Filing_Strategy__c.contains('Filing')) 
   	        {
   	           if(policyState.Filing_Strategy__c == 'Group Filing') 
   	           {
   	               mapGroupFilingPolicyFormDateTime.put(policyState.Policy_Form__c,policyState);
   	              
   	           }
   	           if(policyState.Filing_Strategy__c == 'Compact Filing') 
   	           {
   	               mapCompactFilingPolicyFormDateTime.put(policyState.Policy_Form__c,policyState);
   	               
   	               
   	           }
   	           Filing_Status__c policyStateToUpdate = new Filing_Status__c(id=policyState.Id);
   	           policyStateToUpdate.Filing_Status__c = 'Approved';
   	           lstFilingStatusToUpdate.add(policyStateToUpdate);
   	           setPolicyFormAffected.add(policyState.Policy_Form__c);
   	       }
   	   }
   	   
   	   if(setPolicyFormAffected != null && !setPolicyFormAffected.isEmpty()) 
   	   {
   	       //query group dependent policy form records and set Approval date on policy forms
   	       List<Filing_Status__c> lstPolicyFormsChild = new List<Filing_Status__c>();
   	       lstPolicyFormsChild = DAL_FilingStatus.getByParentIDsAndFilingStrategy(new List<Id>(setPolicyFormAffected));
   	       if(lstPolicyFormsChild != null && !lstPolicyFormsChild.isEmpty())
   	       {
   	           for(Filing_Status__c policyState : lstPolicyFormsChild)
   	           {
   	               if(mapGroupFilingPolicyFormDateTime.containsKey(policyState.Policy_Form__c))
   	               {
   	                   policyState.State_Approval_Date__c = mapGroupFilingPolicyFormDateTime.get(policyState.Policy_Form__c).State_Approval_Date__c;
   	                   policyState.Situs_State__c = mapGroupFilingPolicyFormDateTime.get(policyState.Policy_Form__c).State__c;
   	                   policyState.Filing_Status__c = 'Approved - Dependent Group';
   	                   lstFilingStatusToUpdate.add(policyState);
   	                   
   	               }
   	               if(mapCompactFilingPolicyFormDateTime.containsKey(policyState.Policy_Form__c))
   	               {
   	                   policyState.State_Approval_Date__c = mapCompactFilingPolicyFormDateTime.get(policyState.Policy_Form__c).State_Approval_Date__c;
   	                   policyState.Situs_State__c = mapCompactFilingPolicyFormDateTime.get(policyState.Policy_Form__c).State__c;
   	                   policyState.Filing_Status__c = 'Approved - Dependent Compact';
   	                   lstFilingStatusToUpdate.add(policyState);
   	               }
                        
                        
   	           }
   	           if(lstFilingStatusToUpdate!=null && !lstFilingStatusToUpdate.isEmpty())
   	           {
   	               BaseTriggerHandler.bypass('POLICYSTATEHANDLER');
   	               update lstFilingStatusToUpdate;
   	               BaseTriggerHandler.clearBypass('POLICYSTATEHANDLER');
   	           }
   	           
   	       }
   	       //create Approval_State__c for each situs state
   	       Map<Id,Filing_Status__c> mapSitusStates = new Map<Id,Filing_Status__c>();
   	       mapSitusStates.putAll(mapGroupFilingPolicyFormDateTime);
   	       mapSitusStates.putAll(mapCompactFilingPolicyFormDateTime);
   	       createApprovalState(mapSitusStates);
   	   }
   }
    
   // Requirement to Functionality to update dependent filings when the situs state or compact record is approved
   public void setApprovalStatus()
   {
   	  for(Filing_Status__c fs:newFilingStatus)
   	  {
   	  	if(fs.State_Approval_Date__c  != null)
        {
        	fs.Filing_Status__c = 'Approved';
        }   	  	
   	  }
   }
   
   public void createApprovalState(Map<Id,Filing_Status__c> mapPolicyFromSitusStates) 
   {
      If(mapPolicyFromSitusStates!=null && !mapPolicyFromSitusStates.isEmpty())
      {
          List<Approval_State__c> lstApprovalStateToInsert = new List<Approval_State__c>();
          Set<Id> policyFormsHavePrimaryApprovalState = new Set<Id>();
          //check if policy form has primary Approval_state
          List<Approval_State__c> lstPrimaryApprovalState = new List<Approval_State__c>();
          lstPrimaryApprovalState = DAL_Approval_State.getPrimaryApprovalStateByParentIds(mapPolicyFromSitusStates.keySet());
          for(Approval_State__c approvedState : lstPrimaryApprovalState) 
          {
              policyFormsHavePrimaryApprovalState.add(approvedState.Policy_Form__c);
          }
          for(Filing_Status__c policyState : mapPolicyFromSitusStates.values())
          {
              Approval_State__c situsState = new Approval_State__c();
              situsState.Policy_Form__c = policyState.Policy_Form__c;
              situsState.Approval_Date_Time__c = policyState.State_Approval_Date__c;
              if(!policyFormsHavePrimaryApprovalState.contains(policyState.Policy_Form__c)) 
              {
                  situsState.Is_Primary__c = true;
              }
              situsState.Situs_State__c = policyState.State__c;
              lstApprovalStateToInsert.add(situsState);
          }
          if(lstApprovalStateToInsert!=null && !lstApprovalStateToInsert.isEmpty())
          {
              insert lstApprovalStateToInsert;
          }
      }
   }
    
    
	public void namePolicyStateRecord(Boolean isBefore, Boolean isInsert, List<Filing_Status__c> newList) {
		
		if(isBefore && isInsert){
			//	Retrieve List of Product Names

			//	-- Create Set of Product Spec Ids
			Set<Id> policyIdSet = new Set<Id>();
			for(Filing_Status__c filingstat : newList){
				policyIdSet.add(filingstat.Policy_Form__c);
			}

			//	-- Create Map of Product Spec Id to Product Name
			Map<Id, Policy_Form_Detail__c> policyspecMap = new Map<Id, Policy_Form_Detail__c>(DAL_PolicyFormDetail.getByIds(new List<Id>(policyIdSet)));

			for(Filing_Status__c filingstat : newList){
				if(policyspecMap.containsKey(filingstat.Policy_Form__c)){
					filingstat.Name = policyspecMap.get(filingstat.Policy_Form__c).Name + ' - ' + filingstat.State__c;
				}
			}
		}
	}

	public void policyStateStatusChange(Boolean isAfter, Boolean isUpdate, Map<Id, Filing_Status__c> oldMap, Map<Id, Filing_Status__c> newMap){
		if(isAfter && isUpdate){
			Set<Id> FilingStatSetforUpd = new Set<Id>();

			for(Id key : newMap.keySet()){
				//	Only Process Records with Changed Filing Status
				if(oldMap.get(key).Filing_Status__c != newMap.get(key).Filing_Status__c){
					FilingStatSetforUpd.add(key);
				}
			}

			if(FilingStatSetforUpd.size() > 0)
			{
				List<Product_State_Status__c> pssforUpdList = new List<Product_State_Status__c>();
				for(Product_State_Status__c pss : [Select Id, Filing_Status__c, Filing_Status__r.Filing_Status__c from Product_State_Status__c Where Filing_Status__c in: FilingStatSetforUpd])
				{
					pss.Policy_Form_Status__c = pss.Filing_Status__r.Filing_Status__c;
					pssforUpdList.add(pss);
				}

				//	Update Product State Status with New Filing Status Value
				if(pssforUpdList.size() > 0)
				{
					update pssforUpdList;
				}
			}
		}
	}
    
}