F&GDEV/src/objects/Approval_State__c.object
<CustomObject>
    <fields>
        <fullName>Policy_Form__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Policy Form</label>
        <referenceTo>Policy_Form_Detail__c</referenceTo>
        <relationshipName>Approval_States</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Situs_State__c</fullName>
        <label>Situs_State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>NE</fullName>
                </value>
                <value>
                    <fullName>NV</fullName>
                </value>
                <value>
                    <fullName>NH</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Approved Situs State</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Approval State Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approved Situs States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

F&GDEV/src/objects/Policy_Form_Detail__c.object
<CustomObject>
    <description>Object utilized for Product Development efforts</description>
    <fields>
        <fullName>Approved_States__c</fullName>
        <label>Approved States</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The status field describes whether state approvals have been provided or if the filing is still active and has not received state approvals.</description>
        <inlineHelpText>Whether state approvals have been provided or if the filing is still active and has not received state approvals.</inlineHelpText>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Policy Form</label>
    <nameField>
        <label>Policy Form</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Forms</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

F&GDEV/src/classes/TH_ApprovalState.cls
public class TH_ApprovalState extends BaseTriggerHandler {
	
	
	private List<Approval_State__c> newApprovalState;
    private List<Approval_State__c> oldApprovalState;
    private Map<ID, Approval_State__c> newApprovalStateMap;
    private Map<ID, Approval_State__c> oldApprovalStatelMap;
	
	public TH_ApprovalState()
    {
        oldApprovalState = (List<Approval_State__c>)Trigger.old;
        newApprovalState = (List<Approval_State__c>)Trigger.new;
        newApprovalStateMap = (Map<ID, Approval_State__c>)Trigger.newMap;
        oldApprovalStatelMap = (Map<ID, Approval_State__c>)Trigger.oldMap;
    }
    
     @TestVisible
    protected override void afterInsert()
    {
    	if(TriggerCheck.canRun('TH_APPROVALSTATE'))
        {
    		// Upate the parent object to append the name and set the status to active
    		setApprovedStatesOnPolicyForm(oldApprovalStatelMap, newApprovalStateMap);
    		
        }
    }
    public void setApprovedStatesOnPolicyForm(Map<Id, Approval_State__c> oldMap, Map<Id, Approval_State__c> newMap)
    {
        Set<Id> setPolicyForms = new Set<Id>();
        Map<Id,Set<String>> mapPolicyFormToUpdate = new Map<Id,Set<String>>();
        List<Policy_Form_Detail__c> lstPolicyFormToUpdate = new List<Policy_Form_Detail__c>();
        for(Approval_State__c policyState: newMap.values())
        {
            setPolicyForms.add(policyState.Policy_Form__c);
        }
       
        if(setPolicyForms!=null && !setPolicyForms.isEmpty())
        {
            //query all children of the policyforms
            List<Approval_State__c> lstPolicyState = DAL_Approval_State.getApprovalStateByParentIds(setPolicyForms);
            for(Approval_State__c policyState : lstPolicyState)
            {
                if(mapPolicyFormToUpdate.containsKey(policyState.Policy_Form__c))
                {
                    mapPolicyFormToUpdate.get(policyState.Policy_Form__c).add(policyState.Situs_State__c);  
                } else
                {
                    mapPolicyFormToUpdate.put(policyState.Policy_Form__c, new Set<String>{policyState.Situs_State__c});
                }
            }
            
            for(Id policyFormId: mapPolicyFormToUpdate.keySet())
            {
                Policy_Form_Detail__c pf = new Policy_Form_Detail__c(Id=policyFormId);
                pf.Status__c = 'Active';
                pf.Approved_States__c = String.Join(new List<String>(mapPolicyFormToUpdate.get(policyFormId)),';');
                lstPolicyFormToUpdate.add(pf);
            }
        }
        
        if(lstPolicyFormToUpdate!=null && !lstPolicyFormToUpdate.isEmpty())
        {
            BaseTriggerHandler.bypass('TH_POLICYFORMDETAILHANDLER');
            update lstPolicyFormToUpdate;
            BaseTriggerHandler.clearByPass('TH_POLICYFORMDETAILHANDLER');    
        }
        
    }
}