F&GDEV/src/objects/Filing_Status__c.object
<CustomObject>
    <description>Object utilized for Product Development efforts</description>
    <fields>
        <fullName>Filing_Status__c</fullName>
        <label>Filing Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Pending Act Support</fullName>
                </value>
                <value>
                    <fullName>Filed</fullName>
                </value>
                <value>
                    <fullName>Objection</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Not Filing</fullName>
                </value>
                <value>
                    <fullName>Pending Compact</fullName>
                </value>
                <value>
                    <fullName>Pending Group</fullName>
                </value>
                <value>
                    <fullName>Approved - Dependent Group</fullName>
                </value>
                <value>
                    <fullName>Approved - Compact</fullName>
                </value>
                <value>
                    <fullName>Approved - Exempt</fullName>
                </value>
                <value>
                    <fullName>Approved - Dependent Compact</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Filed with DOI</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Targeted</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Policy_Form__c</fullName>
        <label>Policy Form</label>
        <referenceTo>Policy_Form_Detail__c</referenceTo>
        <relationshipLabel>Policy Form States</relationshipLabel>
        <relationshipName>Filing_Statuses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>NE</fullName>
                </value>
                <value>
                    <fullName>NV</fullName>
                </value>
                <value>
                    <fullName>NH</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Policy Form State</label>
    <nameField>
        <label>Policy Form State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Form States</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

F&GDEV/src/objects/Policy_Form_Detail__c.object
<CustomObject>
    <description>Object utilized for Product Development efforts</description>
    <label>Policy Form</label>
    <nameField>
        <label>Policy Form</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Forms</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

F&GDEV/src/objects/State__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List of supported policy states.</description>
    <label>State</label>
</CustomObject>

F&GDEV/src/classes/CTRL_CreatePolicyFormStates.cls
public class CTRL_CreatePolicyFormStates
{
	
	@AuraEnabled
    public static List<String> getselectOptions(String getFrom,String objectName,String  methodOrFieldName, String parentRecordId) {
        Map<String,String> mapStateOptions = new Map<String,String>();
        mapStateOptions = CTRL_CreateMassPolicyForm.getselectOptions(getFrom,objectName,methodOrFieldName);
        mapStateOptions.keySet().removeAll(policyStatesAlreadyCreated(parentRecordId));
        mapStateOptions.values().sort();
        return mapStateOptions.values();
    }
    
    @AuraEnabled
    public static String createChildPolicyStates(String policyFormId, List<String> selectedStates)
    {
        String message = 'State records created';
        List<Filing_Status__c> lstFilingStatusToInsert = new List<Filing_Status__c>();
        List<Id> policyFormIds = new List<Id>(); 
        policyFormIds.add(Id.valueof(policyFormId));
        Policy_Form_Detail__c parentRecord = DAL_PolicyFormDetail.getByIds(policyFormIds)[0];
        try 
        {
            for(String state : selectedStates)
            {
                Filing_Status__c filingStatusObj = new Filing_Status__c(Policy_Form__c = parentRecord.Id, State__c =state  );
                lstFilingStatusToInsert.add(filingStatusObj);
            }
            
            if(lstFilingStatusToInsert!=null && !lstFilingStatusToInsert.isEmpty()) {
				insert lstFilingStatusToInsert;                
            }
        }catch(Exception ex)
         {
            message = 'Error occured while creating state records' + ex.getMessage();
        }
        
        return message;
    }  
   
   
    private Static Set<String> policyStatesAlreadyCreated(String recordId)
    {
        Set<String> policyStates = new Set<String>();
        List<Id> recordIds = new List<Id>(); 
        recordIds.add(Id.valueof(recordId));
        List<Filing_Status__c> policyFormStates = DAL_FilingStatus.getByParentIds(recordIds);
        for(Filing_Status__c state: policyFormStates) 
        {
            policyStates.add(state.State__c);
        }
        
        return policyStates;
    }
}