F&GDEV/src/objects/Filing_Status__c.object
<CustomObject>
    <description>Object utilized for Product Development efforts</description>
    <fields>
        <fullName>Filing_Notes_Status_Notes__c</fullName>
        <inlineHelpText>Provide high-level comments for reporting purposes and for stakeholders to view quickly.</inlineHelpText>
        <label>Filing Notes Summary</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Filing_Notes__c</fullName>
        <inlineHelpText>Provide detailed filing notes for internal purposes. This field provides additional information that may not be necessary to view in exported reports.</inlineHelpText>
        <label>Filing Notes Detail</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Filing_Status__c</fullName>
        <label>Filing Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Pending Act Support</fullName>
                </value>
                <value>
                    <fullName>Filed</fullName>
                </value>
                <value>
                    <fullName>Objection</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Not Filing</fullName>
                </value>
                <value>
                    <fullName>Pending Compact</fullName>
                </value>
                <value>
                    <fullName>Pending Group</fullName>
                </value>
                <value>
                    <fullName>Approved - Dependent Group</fullName>
                </value>
                <value>
                    <fullName>Approved - Compact</fullName>
                </value>
                <value>
                    <fullName>Approved - Exempt</fullName>
                </value>
                <value>
                    <fullName>Approved - Dependent Compact</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Filed with DOI</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Targeted</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Objection_Deadline_Date__c</fullName>
        <label>Current Objection Deadline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Objection_Received_Date__c</fullName>
        <label>Objection Received Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Objection_Response_Date__c</fullName>
        <label>Most Recent Objection Response Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>State_Approval_Date__c</fullName>
        <inlineHelpText>This should be completed if Exempt or Approved.</inlineHelpText>
        <label>State Approval Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Submitted_to_State_Date__c</fullName>
        <label>Submitted to State Date</label>
        <type>Date</type>
    </fields>
    <label>Policy Form State</label>
    <nameField>
        <label>Policy Form State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Form States</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

F&GDEV/src/classes/W_FilingStatusAggregate.cls
public with sharing class W_FilingStatusAggregate {
	public W_FilingStatusAggregate(){}

	private List<String> pvtFieldList = new List<String>
	{
		'Filing_Status__c','State_Approval_Date__c','Submitted_to_State_Date__c','Objection_Deadline_Date__c','Objection_Received_Date__c','Objection_Response_Date__c','Filing_Notes__c','Filing_Notes_Status_Notes__c'
	};

	public Map<String, AggregatedFieldClass> AggregateFieldMap = new Map<String, AggregatedFieldClass>();

	public class AggregatedFieldClass
	{
		public AggregatedFieldClass(String FieldName, String FieldValue, Boolean isMultiValue, Boolean doOverride){}

		public String FieldName 				{get; set;}
		public String FieldValue 				{get; set;}
		public Boolean isMultiValue 			{get; set;}
		public Boolean doOverride 				{get; set;}
	}

	public void addFilingStatus(Filing_Status__c filingstatus){
		//	keep copy of filing status
		pvtFilingStatusList.add(filingstatus);

		//	iterate object fields and update class aggregate field value
		for(String field : pvtFieldList){
			//	Add field if it is not already mapped
			if(!AggregateFieldMap.containsKey(field)){
				this.AggregateFieldMap.put(field, new AggregatedFieldClass(field, String.valueOf(filingstatus.get(field)), false, false));
			}else{
				//	Update object to specify that field value already exists
				this.AggregateFieldMap.get(field).isMultiValue = true;
			}
		}

	}

	public List<Filing_Status__c> getFilingStatusList(){
		return pvtFilingStatusList;
	}

	//	List of Filing Status Objects
	private List<Filing_Status__c> pvtFilingStatusList = new List<Filing_Status__c>();

}