F&GDEV/src/objects/Filing_Status__c.object
<CustomObject>
    <description>Object utilized for Product Development efforts</description>
    <fields>
        <fullName>Filing_Status__c</fullName>
        <label>Filing Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Pending Act Support</fullName>
                </value>
                <value>
                    <fullName>Filed</fullName>
                </value>
                <value>
                    <fullName>Objection</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Not Filing</fullName>
                </value>
                <value>
                    <fullName>Pending Compact</fullName>
                </value>
                <value>
                    <fullName>Pending Group</fullName>
                </value>
                <value>
                    <fullName>Approved - Dependent Group</fullName>
                </value>
                <value>
                    <fullName>Approved - Compact</fullName>
                </value>
                <value>
                    <fullName>Approved - Exempt</fullName>
                </value>
                <value>
                    <fullName>Approved - Dependent Compact</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Filed with DOI</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Targeted</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Policy_Form__c</fullName>
        <label>Policy Form</label>
        <referenceTo>Policy_Form_Detail__c</referenceTo>
        <relationshipLabel>Policy Form States</relationshipLabel>
        <relationshipName>Filing_Statuses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>NE</fullName>
                </value>
                <value>
                    <fullName>NV</fullName>
                </value>
                <value>
                    <fullName>NH</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Policy Form State</label>
    <nameField>
        <label>Policy Form State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Form States</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

F&GDEV/src/objects/Policy_Form_Detail__c.object
<CustomObject>
    <description>Object utilized for Product Development efforts</description>
    <label>Policy Form</label>
    <nameField>
        <label>Policy Form</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Forms</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

F&GDEV/src/objects/State__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List of supported policy states.</description>
    <label>State</label>
</CustomObject>

F&GDEV/src/classes/PolicyFormDetailHandler.cls
public class PolicyFormDetailHandler extends BaseTriggerHandler {
	
	
	private List<Policy_Form_Detail__c> newPolicyFormDetail;
    private List<Policy_Form_Detail__c> oldPolicyFormDetail;
    private Map<ID, Policy_Form_Detail__c> newPolicyFormDetailMap;
    private Map<ID, Policy_Form_Detail__c> oldPolicyFormDetaillMap;
	
	public PolicyFormDetailHandler()
    {
        oldPolicyFormDetail = (List<Policy_Form_Detail__c>)Trigger.old;
        newPolicyFormDetail = (List<Policy_Form_Detail__c>)Trigger.new;
        newPolicyFormDetailMap = (Map<ID, Policy_Form_Detail__c>)Trigger.newMap;
        oldPolicyFormDetaillMap = (Map<ID, Policy_Form_Detail__c>)Trigger.oldMap;
    }

  @TestVisible
    protected override void afterUpdate()
    {
		if(TriggerCheck.canRun('TH_POLICYFORMDETAILHANDLER'))
		{
			changePolicyFormStatesName(newPolicyFormDetail,oldPolicyFormDetaillMap,newPolicyFormDetailMap);
		}
    }
    
    public void changePolicyFormStatesName(List<Policy_Form_Detail__c> newPolicyFormDetail,
     										 Map<Id, Policy_Form_Detail__c> oldPolicyFormDetaillMap, 
     										 Map<Id, Policy_Form_Detail__c> newPolicyFormDetailMap)
     {
        	List<Id> idsforWhichNameChanged = new List<Id>();
        	for(Policy_Form_Detail__c ps: newPolicyFormDetail)
        	{
        		if(oldPolicyFormDetaillMap.get(ps.Id).Name != ps.Name)
        		{
        			idsforWhichNameChanged.add(ps.Id);
        		}
        	}
        	
        	
        	if(! idsforWhichNameChanged.isEmpty())
        	{
            	Map<Id,List<Filing_Status__c>> byParentIdMap = DAL_FilingStatus.getByParentIdMap(idsforWhichNameChanged);
            	List<Filing_Status__c> toUpdatePolicyFormState = new List<Filing_Status__c>();
                for(Id i: idsforWhichNameChanged)
                {
                    for(Filing_Status__c s: byParentIdMap.get(i))
                    {
                        toUpdatePolicyFormState.add(new Filing_Status__c(Id=s.Id,
                                                       Name = newPolicyFormDetailMap.get(s.Policy_Form__c).Name+'-'+s.State__c));
                    }
                }
            	if(!toUpdatePolicyFormState.isEmpty())
            	{
            		update toUpdatePolicyFormState;
            	}
        	}
        	
     }

}