F&GDEV/src/objects/Filing_Status__c.object
<CustomObject>
    <description>Object utilized for Product Development efforts</description>
    <fields>
        <fullName>Filing_Status__c</fullName>
        <label>Filing Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Pending Act Support</fullName>
                </value>
                <value>
                    <fullName>Filed</fullName>
                </value>
                <value>
                    <fullName>Objection</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Not Filing</fullName>
                </value>
                <value>
                    <fullName>Pending Compact</fullName>
                </value>
                <value>
                    <fullName>Pending Group</fullName>
                </value>
                <value>
                    <fullName>Approved - Dependent Group</fullName>
                </value>
                <value>
                    <fullName>Approved - Compact</fullName>
                </value>
                <value>
                    <fullName>Approved - Exempt</fullName>
                </value>
                <value>
                    <fullName>Approved - Dependent Compact</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Filed with DOI</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Targeted</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Filing_Strategy__c</fullName>
        <label>Filing Strategy</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Individual Filing</fullName>
                </value>
                <value>
                    <fullName>Compact Filing</fullName>
                </value>
                <value>
                    <fullName>Compact Dependent</fullName>
                </value>
                <value>
                    <fullName>Group Filing</fullName>
                </value>
                <value>
                    <fullName>Group Dependent</fullName>
                </value>
                <value>
                    <fullName>Exempt</fullName>
                </value>
                <value>
                    <fullName>File &amp; Use</fullName>
                </value>
                <value>
                    <fullName>Not Filing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Policy_Form__c</fullName>
        <label>Policy Form</label>
        <referenceTo>Policy_Form_Detail__c</referenceTo>
        <relationshipLabel>Policy Form States</relationshipLabel>
        <relationshipName>Filing_Statuses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>State_Approval_Date__c</fullName>
        <inlineHelpText>This should be completed if Exempt or Approved.</inlineHelpText>
        <label>State Approval Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>NE</fullName>
                </value>
                <value>
                    <fullName>NV</fullName>
                </value>
                <value>
                    <fullName>NH</fullName>
                </value>
                <value>
                    <fullName>WY</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Policy Form State</label>
    <nameField>
        <label>Policy Form State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Form States</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

F&GDEV/src/objects/Filing_Strategy__c.object
<CustomObject>
    <label>Filing Strategy</label>
    <nameField>
        <label>Filing Strategy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Filing Strategies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

F&GDEV/src/objects/Policy_Form_Detail__c.object
<CustomObject>
    <description>Object utilized for Product Development efforts</description>
    <fields>
        <fullName>Filing_Strategy__c</fullName>
        <label>Filing Strategy</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Individual</fullName>
                </value>
                <value>
                    <fullName>IIPRC</fullName>
                </value>
                <value>
                    <fullName>Group</fullName>
                </value>
                <value>
                    <fullName>TBD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Policy Form</label>
    <nameField>
        <label>Policy Form</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Forms</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

F&GDEV/src/objects/State__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List of supported policy states.</description>
    <label>State</label>
</CustomObject>

F&GDEV/src/classes/PolicyStateHandlerTest.cls
@isTest
private class PolicyStateHandlerTest {
	
	@isTest static void CreatePolicyForms() {
		List<String> TestStateList = new List<String>{'AL', 'LA', 'ID', 'WY', 'FL'};

		// Batch Create Policy Forms
		List<Policy_Form_Detail__c> policyformList = (List<Policy_Form_Detail__c>)SmartFactory.createSObjectList('Policy_Form_Detail__c', false, 10);
		Integer i = 0;
		for(Policy_Form_Detail__c policyform : policyformList){
			policyform.Name = 'Policy Spec Name - GRP ' + i;
			i += 1;
		}
		insert policyformList;

		Map<Id, Policy_Form_Detail__c> policyformMap = new Map<Id, Policy_Form_Detail__c>([Select Id, Name from Policy_Form_Detail__c]);

		//	Create Policy State Objects for Insert
		List<Filing_Status__c> filingstatList = new List<Filing_Status__c>();
		for(String statecode : TestStateList){
			for(Policy_Form_Detail__c policyform : policyformList){
				filingstatList.add(new Filing_Status__c(Policy_Form__c = policyform.Id, State__c = statecode, Filing_Status__c='Filed'));
			}
		}
		insert filingstatList;

		//	Validate Names of State Availability Records
		for(Filing_Status__c filingstat : [Select Name, Policy_Form__c, State__c from Filing_Status__c])
		{
			System.assertEquals(policyformMap.get(filingstat.Policy_Form__c).Name + ' - ' + filingstat.State__c, filingstat.Name);
		}

		for(Filing_Status__c status : filingstatList){
			status.Filing_Status__c = 'Not Started';
		}
		update filingstatList;
	}
	
	static testmethod void  UpdatePolicyForms()
	{
	    List<String> TestStateList = new List<String>{'AL', 'LA', 'ID', 'WY', 'FL'};

		// Batch Create Policy Forms
		List<Policy_Form_Detail__c> policyformList = (List<Policy_Form_Detail__c>)SmartFactory.createSObjectList('Policy_Form_Detail__c', false, 10);
		Integer i = 0;
		for(Policy_Form_Detail__c policyform : policyformList){
			policyform.Name = 'Policy Spec Name - GRP ' + i;
			i += 1;
		}
		insert policyformList;

		Map<Id, Policy_Form_Detail__c> policyformMap = new Map<Id, Policy_Form_Detail__c>([Select Id, Name from Policy_Form_Detail__c]);

		//	Create Policy State Objects for Insert
		List<Filing_Status__c> filingstatList = new List<Filing_Status__c>();
		for(String statecode : TestStateList){
			for(Policy_Form_Detail__c policyform : policyformList){
				filingstatList.add(new Filing_Status__c(Policy_Form__c = policyform.Id, State__c = statecode, Filing_Status__c='Filed'));
			}
		}
		insert filingstatList;
        Test.startTest();
		for(Filing_Status__c status : filingstatList){
			status.Filing_Strategy__c = 'Group Dependent';
		}
		filingstatList[0].Filing_Strategy__c = 'Group Filing';
		filingstatList[0].State_Approval_Date__c = Date.today()+30;
		update filingstatList;
		Test.stopTest();
		for(Filing_Status__c assertFilingStatus : [Select Filing_Status__c, State_Approval_Date__c from Filing_Status__c where Policy_Form__c=:policyformList[0].Id])
		{
		    System.assertEquals('Approved - Dependent Group', assertFilingStatus.Filing_Status__c);
		    System.assertNotEquals(null, assertFilingStatus.State_Approval_Date__c);
		}
	}


}