F&GDEV/src/objects/Filing_Status__c.object
<CustomObject>
    <description>Object utilized for Product Development efforts</description>
    <fields>
        <fullName>Filing_Status__c</fullName>
        <label>Filing Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Pending Act Support</fullName>
                </value>
                <value>
                    <fullName>Filed</fullName>
                </value>
                <value>
                    <fullName>Objection</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Not Filing</fullName>
                </value>
                <value>
                    <fullName>Pending Compact</fullName>
                </value>
                <value>
                    <fullName>Pending Group</fullName>
                </value>
                <value>
                    <fullName>Approved - Dependent Group</fullName>
                </value>
                <value>
                    <fullName>Approved - Compact</fullName>
                </value>
                <value>
                    <fullName>Approved - Exempt</fullName>
                </value>
                <value>
                    <fullName>Approved - Dependent Compact</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Filed with DOI</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Targeted</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Policy Form State</label>
    <nameField>
        <label>Policy Form State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Form States</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

F&GDEV/src/objects/Product_State_Status__c.object
<CustomObject>
    <description>Value set via trigger, to match the filing status on the related Policy Form State record, so that it can be used in a roll-up summary field on the Product State record.</description>
    <fields>
        <fullName>Filing_Status__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Policy Form State</label>
        <referenceTo>Filing_Status__c</referenceTo>
        <relationshipLabel>Product State Policy Form Associations</relationshipLabel>
        <relationshipName>Product_State_Statuses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Policy_Form_Status__c</fullName>
        <label>Policy Form Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Product State Policy Form Association</label>
    <nameField>
        <displayFormat>PSPF - {0000}</displayFormat>
        <label>Product State Policy Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product State Policy Form Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

F&GDEV/src/classes/ProductStatePolicyAssocHandler.cls
public with sharing class ProductStatePolicyAssocHandler  extends BaseTriggerHandler {
	
	
	private List<Product_State_Status__c> newProductStateStatus;
    private List<Product_State_Status__c> oldProductStateStatuss;
    private Map<ID, Product_State_Status__c> newProductStateStatusMap;
    private Map<ID, Product_State_Status__c> oldProductStateStatuslMap;
	
	public ProductStatePolicyAssocHandler()
    {
        oldProductStateStatuss = (List<Product_State_Status__c>)Trigger.old;
        newProductStateStatus = (List<Product_State_Status__c>)Trigger.new;
        newProductStateStatusMap = (Map<ID, Product_State_Status__c>)Trigger.newMap;
        oldProductStateStatuslMap = (Map<ID, Product_State_Status__c>)Trigger.oldMap;
    }
    
    
     @TestVisible
    protected override void beforeInsert()
    {
    	if(TriggerCheck.canRun('TH_PRODUCTSTATEPOLICYASSOCHANDLER'))
        {
    		transferStatus(Trigger.isBefore, Trigger.isInsert, newProductStateStatus);
        }
    }
    
	public void transferStatus(Boolean isBefore, Boolean isInsert, List<Product_State_Status__c> newList)
	 {
		if(isBefore && isInsert){
			//	Retrieve List of Product Names

			//	-- Create Set of Policy Ids
			Set<Id> FilingStatIdSet = new Set<Id>();
			for(Product_State_Status__c pss : newList){
				FilingStatIdSet.add(pss.Filing_Status__c);
			}

			//	-- Create Map of Product Spec Id to Product Name
			Map<Id, Filing_Status__c> filingstatMap = new Map<Id, Filing_Status__c>([Select Id, Filing_Status__c from Filing_Status__c Where Id in:FilingStatIdSet]);

			for(Product_State_Status__c prodstatstatus : newList){
				if(filingstatMap.containsKey(prodstatstatus.Filing_Status__c)){
					prodstatstatus.Policy_Form_Status__c = filingstatMap.get(prodstatstatus.Filing_Status__c).Filing_Status__c;
				}
			}
		}
	}
}