F&GDEV/src/objects/Filing_Status__c.object
<CustomObject>
    <description>Object utilized for Product Development efforts</description>
    <fields>
        <fullName>Feature_Variation_Description__c</fullName>
        <inlineHelpText>Describe the variation detail that relates to the feature.</inlineHelpText>
        <label>Feature Variation Description</label>
        <length>131027</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Filing_Status__c</fullName>
        <label>Filing Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Pending Act Support</fullName>
                </value>
                <value>
                    <fullName>Filed</fullName>
                </value>
                <value>
                    <fullName>Objection</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Not Filing</fullName>
                </value>
                <value>
                    <fullName>Pending Compact</fullName>
                </value>
                <value>
                    <fullName>Pending Group</fullName>
                </value>
                <value>
                    <fullName>Approved - Dependent Group</fullName>
                </value>
                <value>
                    <fullName>Approved - Compact</fullName>
                </value>
                <value>
                    <fullName>Approved - Exempt</fullName>
                </value>
                <value>
                    <fullName>Approved - Dependent Compact</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Filed with DOI</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Targeted</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Form_Variation_Description__c</fullName>
        <inlineHelpText>Describe the variation detail that relates to the form.</inlineHelpText>
        <label>Form Variation Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Policy_Form__c</fullName>
        <label>Policy Form</label>
        <referenceTo>Policy_Form_Detail__c</referenceTo>
        <relationshipLabel>Policy Form States</relationshipLabel>
        <relationshipName>Filing_Statuses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>NE</fullName>
                </value>
                <value>
                    <fullName>NV</fullName>
                </value>
                <value>
                    <fullName>NH</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Policy Form State</label>
    <nameField>
        <label>Policy Form State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Form States</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

F&GDEV/src/objects/Policy_Form_Detail__c.object
<CustomObject>
    <description>Object utilized for Product Development efforts</description>
    <fields>
        <fullName>Insurance_Type__c</fullName>
        <label>Insurance Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Annuity</fullName>
                </value>
                <value>
                    <fullName>Life</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Policy_Form_Type__c</fullName>
        <label>Policy Form Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Base Policy Form</fullName>
                </value>
                <value>
                    <fullName>Rider Policy Form</fullName>
                </value>
                <value>
                    <fullName>Application</fullName>
                </value>
                <value>
                    <fullName>Endorsement</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The status field describes whether state approvals have been provided or if the filing is still active and has not received state approvals.</description>
        <inlineHelpText>Whether state approvals have been provided or if the filing is still active and has not received state approvals.</inlineHelpText>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Policy Form</label>
    <nameField>
        <label>Policy Form</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Forms</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

F&GDEV/src/objects/State__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List of supported policy states.</description>
    <label>State</label>
</CustomObject>

F&GDEV/src/classes/CTRL_DeletePolicyFormStates_T.cls
@isTest
private class CTRL_DeletePolicyFormStates_T 
{
    public static User admin_User;
    public static Integer count =1;
    public static string SYSTEM_ADMINISTRATOR_PROFILE ='System Administrator';
    public static Policy_Form_Detail__c policyForm;
    public static List<Filing_Status__c> policyState = new List<Filing_Status__c>();
    
     static void testData() {
    
        admin_User = TestDataFactory.createUser(true,'',SYSTEM_ADMINISTRATOR_PROFILE);
        
        insert admin_User;
        System.runAs(admin_User) {
            TestDataFactory.initStateList();
            Map<String,Object> mapPolicyForm = new Map<String,Object>();
            mapPolicyForm.put('Name','Policy Form Test');
            mapPolicyForm.put('Insurance_Type__c','Annuity');
            mapPolicyForm.put('Insurance_Type__c','Annuity');
            mapPolicyForm.put('Policy_Form_Type__c','Base Policy Form');
            mapPolicyForm.put('Status__c','Active');
            policyForm =(Policy_Form_Detail__c)TestDataFactory.operationOnObjectRecord('insert', 'Policy_Form_Detail__c', mapPolicyForm);
            //now create related policy form state records
            Map<String,Object> mapPolicyFormStateAL = new Map<String,Object>();
            mapPolicyFormStateAL.put('Name','Policy Form Test - AL');
            mapPolicyFormStateAL.put('State__c','AL');
            mapPolicyFormStateAL.put('Policy_Form__c',policyForm.Id);
            mapPolicyFormStateAL.put('Form_Variation_Description__c','test description');
            mapPolicyFormStateAL.put('Feature_Variation_Description__c','test description');
            
            Map<String,Object> mapPolicyFormStateDE = new Map<String,Object>();
            mapPolicyFormStateDE.put('Name','Policy Form Test - DE');
            mapPolicyFormStateDE.put('State__c','DE');
            mapPolicyFormStateDE.put('Policy_Form__c',policyForm.Id);
            mapPolicyFormStateDE.put('Form_Variation_Description__c','test description');
            mapPolicyFormStateDE.put('Feature_Variation_Description__c','test description');
            
            Map<String,Object> mapPolicyFormStateCO = new Map<String,Object>();
            mapPolicyFormStateCO.put('Name','Policy Form Test - CO');
            mapPolicyFormStateCO.put('State__c','CO');
            mapPolicyFormStateCO.put('Policy_Form__c',policyForm.Id);
            mapPolicyFormStateCO.put('Form_Variation_Description__c','test description');
            mapPolicyFormStateCO.put('Feature_Variation_Description__c','test description');
            
            policyState.add((Filing_Status__c)TestDataFactory.operationOnObjectRecord(null, 'Filing_Status__c', mapPolicyFormStateAL));
            policyState.add((Filing_Status__c)TestDataFactory.operationOnObjectRecord(null, 'Filing_Status__c', mapPolicyFormStateDE));
            policyState.add((Filing_Status__c)TestDataFactory.operationOnObjectRecord(null, 'Filing_Status__c', mapPolicyFormStateCO));
            
            insert policyState;
            
            
        }
     }   
	
	private static testMethod void testGetDeleteablePolicyStates() {
        testData();
        Test.startTest();
        List<Filing_Status__c> lstAssertStates = CTRL_DeletePolicyFormStates.getDeleteablePolicyStates(policyForm.Id);
        System.assertEquals(3, lstAssertStates.size());
        Test.stopTest();
	}
	
	private static testMethod void testDeleteSelectedStateRecord() {
	    testData();
        Test.startTest();
        String message = CTRL_DeletePolicyFormStates.DeleteSelectedStateRecord(policyState);
        System.assertEquals('Delete Successful', message);
        //test alternate path
        String message2 = CTRL_DeletePolicyFormStates.DeleteSelectedStateRecord(policyState);
        System.assert(message2.contains('Error Occured!!'));
        Test.stopTest();
	}

}