F&GDEV/src/objects/Filing_Status__c.object
<CustomObject>
    <description>Object utilized for Product Development efforts</description>
    <fields>
        <fullName>Feature_Variation_Description__c</fullName>
        <inlineHelpText>Describe the variation detail that relates to the feature.</inlineHelpText>
        <label>Feature Variation Description</label>
        <length>131027</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Filing_Status__c</fullName>
        <label>Filing Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Pending Act Support</fullName>
                </value>
                <value>
                    <fullName>Filed</fullName>
                </value>
                <value>
                    <fullName>Objection</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Not Filing</fullName>
                </value>
                <value>
                    <fullName>Pending Compact</fullName>
                </value>
                <value>
                    <fullName>Pending Group</fullName>
                </value>
                <value>
                    <fullName>Approved - Dependent Group</fullName>
                </value>
                <value>
                    <fullName>Approved - Compact</fullName>
                </value>
                <value>
                    <fullName>Approved - Exempt</fullName>
                </value>
                <value>
                    <fullName>Approved - Dependent Compact</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Filed with DOI</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Targeted</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Filing_Strategy__c</fullName>
        <label>Filing Strategy</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Individual Filing</fullName>
                </value>
                <value>
                    <fullName>Compact Filing</fullName>
                </value>
                <value>
                    <fullName>Compact Dependent</fullName>
                </value>
                <value>
                    <fullName>Group Filing</fullName>
                </value>
                <value>
                    <fullName>Group Dependent</fullName>
                </value>
                <value>
                    <fullName>Exempt</fullName>
                </value>
                <value>
                    <fullName>File &amp; Use</fullName>
                </value>
                <value>
                    <fullName>Not Filing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Form_Variation_Description__c</fullName>
        <inlineHelpText>Describe the variation detail that relates to the form.</inlineHelpText>
        <label>Form Variation Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Policy_Form__c</fullName>
        <label>Policy Form</label>
        <referenceTo>Policy_Form_Detail__c</referenceTo>
        <relationshipLabel>Policy Form States</relationshipLabel>
        <relationshipName>Filing_Statuses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>NE</fullName>
                </value>
                <value>
                    <fullName>NV</fullName>
                </value>
                <value>
                    <fullName>NH</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Policy Form State</label>
    <nameField>
        <label>Policy Form State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Form States</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

F&GDEV/src/objects/Filing_Strategy__c.object
<CustomObject>
    <label>Filing Strategy</label>
    <nameField>
        <label>Filing Strategy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Filing Strategies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

F&GDEV/src/objects/Policy_Form_Detail__c.object
<CustomObject>
    <description>Object utilized for Product Development efforts</description>
    <fields>
        <fullName>Filing_Strategy__c</fullName>
        <label>Filing Strategy</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Individual</fullName>
                </value>
                <value>
                    <fullName>IIPRC</fullName>
                </value>
                <value>
                    <fullName>Group</fullName>
                </value>
                <value>
                    <fullName>TBD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Insurance_Type__c</fullName>
        <label>Insurance Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Annuity</fullName>
                </value>
                <value>
                    <fullName>Life</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Policy Form</label>
    <nameField>
        <label>Policy Form</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Forms</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

F&GDEV/src/objects/State__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List of supported policy states.</description>
    <label>State</label>
</CustomObject>

F&GDEV/src/classes/DAL_FilingStatus_T.cls
@isTest
private class DAL_FilingStatus_T {

    public static User admin_User;
    public static Integer count =1;
    public static string SYSTEM_ADMINISTRATOR_PROFILE ='System Administrator';
    public static List<Filing_Status__c> filingStatus = new List<Filing_Status__c>();
    public static List<Policy_Form_Detail__c> policyForms = new List<Policy_Form_Detail__c>();
    
    static void testData()
    {
    
        admin_User = TestDataFactory.createUser(true,'',SYSTEM_ADMINISTRATOR_PROFILE);
        
        insert admin_User;
        System.runAs(admin_User)
        {
        	
        	Map<String,Object>  policyFormsMap = new Map<String,Object>();
            policyFormsMap.put('Insurance_Type__c','Life');
            policyFormsMap.put('Filing_Strategy__c','Individual');
        	for(Integer i = 0 ; i <count; i++)
            {
                policyForms.add((Policy_Form_Detail__c) TestDataFactory.operationOnObjectRecord(null, 'Policy_Form_Detail__c', policyFormsMap));
            }
            insert policyForms; 
            
            Map<String,Object> filingStatusMap = new Map<String,Object>();
            filingStatusMap.put('Policy_Form__c',policyForms[0].Id);
            filingStatusMap.put('State__c','Al');
            filingStatusMap.put('Form_Variation_Description__c','testDescription');
            filingStatusMap.put('Feature_Variation_Description__c','testFeatureDescription');
            filingStatusMap.put('Filing_Strategy__c','Group Dependent');
            for(Integer i = 0 ; i <count; i++)
            {
                filingStatus.add((Filing_Status__c) TestDataFactory.operationOnObjectRecord(null, 'Filing_Status__c', filingStatusMap));
            }
            insert filingStatus; 
        } 
    
    }
    
    static testMethod void getByIdsMapTest() {
     
     testData();
     Test.startTest();
     List<Id> policyFormsIds  = new List<Id>();
     for(Policy_Form_Detail__c policyForm:policyForms)
     {
     	policyFormsIds.add(policyForm.id);
     }
     DAL_FilingStatus.getByParentIds(policyFormsIds);
     DAL_FilingStatus.getByParentIdMap(policyFormsIds);
     DAL_FilingStatus.getByParentIDsAndFilingStrategy(policyFormsIds);
     Test.stopTest();
        
    }
}