F&GDEV/src/objects/Filing_Status__c.object
<CustomObject>
    <description>Object utilized for Product Development efforts</description>
    <fields>
        <fullName>Filing_Status__c</fullName>
        <label>Filing Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Pending Act Support</fullName>
                </value>
                <value>
                    <fullName>Filed</fullName>
                </value>
                <value>
                    <fullName>Objection</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Not Filing</fullName>
                </value>
                <value>
                    <fullName>Pending Compact</fullName>
                </value>
                <value>
                    <fullName>Pending Group</fullName>
                </value>
                <value>
                    <fullName>Approved - Dependent Group</fullName>
                </value>
                <value>
                    <fullName>Approved - Compact</fullName>
                </value>
                <value>
                    <fullName>Approved - Exempt</fullName>
                </value>
                <value>
                    <fullName>Approved - Dependent Compact</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Filed with DOI</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Targeted</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Policy Form State</label>
    <nameField>
        <label>Policy Form State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Form States</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

F&GDEV/src/objects/Product_State_Status__c.object
<CustomObject>
    <description>Value set via trigger, to match the filing status on the related Policy Form State record, so that it can be used in a roll-up summary field on the Product State record.</description>
    <fields>
        <fullName>Filing_Status__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Policy Form State</label>
        <referenceTo>Filing_Status__c</referenceTo>
        <relationshipLabel>Product State Policy Form Associations</relationshipLabel>
        <relationshipName>Product_State_Statuses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product State Policy Form Association</label>
    <nameField>
        <displayFormat>PSPF - {0000}</displayFormat>
        <label>Product State Policy Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product State Policy Form Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

F&GDEV/src/classes/CTRL_DeletePolicyFormStates.cls
public class CTRL_DeletePolicyFormStates {
    //Method to fetch the policystates which can be deleted
    Private static final string SUCCESS_MESSAGE = 'Delete Successful';
    Private static final string ERROR_MESSAGE = 'Error Occured!!';
    @Auraenabled
    public static List<Filing_Status__c> getDeleteablePolicyStates(String parentRecordId) {
        //List<PolicyFormStateWrapper> lstPolicyStateWrapper;
        //fetch all policy form states
        Map<Id,List<Filing_Status__c>> mapPolicyFormStatesWithParentID = DAL_FilingStatus.getByParentIdMap(new List<Id>{parentRecordId});
        //convert the list of Filing status to id map
        Map<Id,Filing_Status__c> mapPolicyFormStates = new Map<Id,Filing_Status__c>(mapPolicyFormStatesWithParentID.get(parentRecordId));
                                    
        if(mapPolicyFormStates!=null && !mapPolicyFormStates.isEmpty()) {
            //fetch the list of Filing_Status__c records which has association with junction object
            Map<Id,Product_State_Status__c> mapProductStateStatus = new Map<Id,Product_State_Status__c>();
            mapProductStateStatus = DAL_ProductStatePolicyFormAssociation.getByfillingStatusMap(new List<Id>(mapProductStateStatus.keySet()));
            //remove the products which has association
            mapPolicyFormStates.keySet().removeAll(mapProductStateStatus.keySet());
        }
        List<Filing_Status__c> returnVal = mapPolicyFormStates.values();
        returnVal.sort();
        return returnVal;

    }
    @Auraenabled
    public static String deleteSelectedStateRecord(List<Filing_Status__c> selectedStates){
        String message=SUCCESS_MESSAGE;
        Savepoint sp = Database.setSavepoint();
        try {
            
            if(selectedStates!=null && !selectedStates.isEmpty()) {
                delete selectedStates;
            }
        } catch(Exception ex) {
            Database.rollback(sp);
            message = ERROR_MESSAGE + ex.getMessage();
            return message;
        }
        
        return message;
    }
}