F&GDEV/src/objects/Filing_Status__c.object
<CustomObject>
    <description>Object utilized for Product Development efforts</description>
    <fields>
        <fullName>Filing_Status__c</fullName>
        <label>Filing Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Pending Act Support</fullName>
                </value>
                <value>
                    <fullName>Filed</fullName>
                </value>
                <value>
                    <fullName>Objection</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Not Filing</fullName>
                </value>
                <value>
                    <fullName>Pending Compact</fullName>
                </value>
                <value>
                    <fullName>Pending Group</fullName>
                </value>
                <value>
                    <fullName>Approved - Dependent Group</fullName>
                </value>
                <value>
                    <fullName>Approved - Compact</fullName>
                </value>
                <value>
                    <fullName>Approved - Exempt</fullName>
                </value>
                <value>
                    <fullName>Approved - Dependent Compact</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Filed with DOI</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Targeted</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>NE</fullName>
                </value>
                <value>
                    <fullName>NV</fullName>
                </value>
                <value>
                    <fullName>NH</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Policy Form State</label>
    <nameField>
        <label>Policy Form State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Form States</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

F&GDEV/src/objects/Marketing_Materials__c.object
<CustomObject>
    <description>Object utilized for Product Development efforts</description>
    <label>Marketing Materials</label>
    <nameField>
        <displayFormat>MM-{0000}</displayFormat>
        <label>Marketing Materials Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Marketing Materials</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

F&GDEV/src/objects/Marketing_to_Product_State_Association__c.object
<CustomObject>
    <fields>
        <fullName>Marketing_Materials__c</fullName>
        <label>Marketing Materials</label>
        <referenceTo>Marketing_Materials__c</referenceTo>
        <relationshipName>Marketing_to_Product_State_Association</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Marketing to Product Association</label>
    <nameField>
        <displayFormat>MPS-{0000}</displayFormat>
        <label>Marketing to Product State Association</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Marketing to Product Association</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

F&GDEV/src/objects/PlanCode__c.object
<CustomObject>
    <fields>
        <fullName>PlanCode__c</fullName>
        <externalId>true</externalId>
        <label>Plan Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Plan Code</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plan Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

F&GDEV/src/objects/Product_Specification__c.object
<CustomObject>
    <description>Object utilized for Product Development efforts</description>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

F&GDEV/src/objects/Product_State_Status__c.object
<CustomObject>
    <description>Value set via trigger, to match the filing status on the related Policy Form State record, so that it can be used in a roll-up summary field on the Product State record.</description>
    <fields>
        <fullName>Filing_Status__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Policy Form State</label>
        <referenceTo>Filing_Status__c</referenceTo>
        <relationshipLabel>Product State Policy Form Associations</relationshipLabel>
        <relationshipName>Product_State_Statuses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Policy_Form_Status__c</fullName>
        <label>Policy Form Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_State_Availability__c</fullName>
        <label>Product State</label>
        <referenceTo>State_Availability__c</referenceTo>
        <relationshipLabel>Product State Policy Form Associations</relationshipLabel>
        <relationshipName>Product_State_Statuses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Product State Policy Form Association</label>
    <nameField>
        <displayFormat>PSPF - {0000}</displayFormat>
        <label>Product State Policy Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product State Policy Form Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

F&GDEV/src/objects/Product_to_Plan_Code_Association__c.object
<CustomObject>
    <label>Product to Plan Code Association</label>
    <nameField>
        <displayFormat>PCA-{0000}</displayFormat>
        <label>Product to Plan Code Association Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product to Plan Code Association</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

F&GDEV/src/objects/State__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List of supported policy states.</description>
    <label>State</label>
</CustomObject>

F&GDEV/src/objects/State_Availability__c.object
<CustomObject>
    <description>Object utilized for Product Development efforts</description>
    <fields>
        <fullName>Product_Specification__c</fullName>
        <label>Product Specification</label>
        <referenceTo>Product_Specification__c</referenceTo>
        <relationshipName>Product_State_Availabilities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>NC</fullName>
                </value>
                <value>
                    <fullName>ND</fullName>
                </value>
                <value>
                    <fullName>NE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Product State</label>
    <nameField>
        <label>Product State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product States</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

F&GDEV/src/classes/HLPR_ProductCloneWithChildRecords.cls
//Controller class to clone product and it's child records
public class HLPR_ProductCloneWithChildRecords {
   
    //private static final String SUCCESS_MESSAGE = 'Clone is Successful you will be redirected to new Record';
    private static final String ERROR_MESSAGE = 'Error Occurred!!';
    public Id recordId {get;set;}
    public String parentObjName {get;set;}
    public List<ChildObjectWrapper> childObjWrapperList {get;set;}
    private final Set<String> setSTRChildObjectsToBeConverted = new Set<String>{'State_Availability__c', 
    																			'PlanCode__c',
    																			'Marketing_Materials__c',
    																			'Product_State_Status__c',
    																			'Product_to_Plan_Code_Association__c',
    																			'Marketing_to_Product_State_Association__c'};
        
    //constructor
    public HLPR_ProductCloneWithChildRecords(String recordId) {
        this.recordID = recordId;
        childObjWrapperList = new List<ChildObjectWrapper>();
        parentObjName = UtilityClass.getObjectNameFromId(recordId);
        List<Schema.ChildRelationship> childObjList = UtilityClass.getChildRelationshipsFromId(recordId);
        for(Schema.ChildRelationship child : childObjList) {
            String childObjectName = (String)child.getChildSObject().getDescribe().getName();
            if(child.getChildSObject().getDescribe().isQueryable() && setSTRChildObjectsToBeConverted.contains(child.getChildSObject().getDescribe().getName())){
                String fieldName = String.valueOf(child.getField());
                if(child.getField().getDescribe().isCreateable()) {
                    childObjWrapperList.add(new ChildObjectWrapper(child.getChildSObject().getDescribe().getName(),true,recordId,String.valueOf(child.getField())));
                }
            }
        }
    }
    
    
    public String cloneWithChildren(String parentObjectNewName) {
        SavePoint sp = Database.setSavepoint();
        String message = '';
        try {
            //get skipped fields list for the parentobject
            Map<String,Set<String>> mapChildObjSkipList  = new Map<String,Set<String>>();
            mapChildObjSkipList = DAL_ObjectCloneSkippedField.getChildSkipListByParentName(parentObjName);
            // Clone parent object record first
            List<Sobject> clonedParentObj = UtilityClass.cloneObject(parentObjName,recordId,true,null,null,mapChildObjSkipList);
            clonedParentObj[0].put('Name',parentObjectNewName);
            BaseTriggerHandler.bypass('PRODUCTSPECIFICATIONHANDLER');
            insert clonedParentObj;
            BaseTriggerHandler.clearBypass('PRODUCTSPECIFICATIONHANDLER');
            // Clone child records
            
            List<sobject> childObjList = new List<sobject>();
            if(childObjWrapperList.size() > 0) {
                for(ChildObjectWrapper obj : childObjWrapperList) {
                    List<Sobject> clonedChildObj = UtilityClass.cloneObject(obj.objName,obj.recordId,false,obj.relationshipName,clonedParentObj.get(0).Id,mapChildObjSkipList);
                    if(clonedChildObj.size() > 0){
                        childObjList.addAll(clonedChildObj);
                    }
                }
            }
            Database.SaveResult[] lstSaveResult = Database.insert(childObjList,true);
            // Iterate through each returned result
			for (Database.SaveResult sr : lstSaveResult) {
			    if (sr.isSuccess()) {
			        // Operation was successful, so get the ID of the record that was processed
			        System.debug('Successfully inserted record ID: ' + sr.getId());
			    }
			    else {
			        // Operation failed, so get all errors                
			        for(Database.Error err : sr.getErrors()) {
			            System.debug('The following error has occurred.');                    
			            System.debug(err.getStatusCode() + ': ' + err.getMessage());
			            System.debug('fields that affected this error: ' + err.getFields());
			        }
			    }
			}    
            message = String.valueOf(clonedParentObj[0].get('Id'));
            cloneProductStateStatuses(message);
            
            // call the future method only after the code control reaches here and delete records
            cloneAttachmentsToFiles(String.valueOf(recordId), String.valueOf(clonedParentObj[0].Id));
            
        } catch(Exception ex) {
            Database.rollback(sp);
            message = ERROR_MESSAGE+ ex.getMessage();
        }
        return message;
    }
   
   
   
    @future
    private static void cloneAttachmentsToFiles(String oldProductFormId, String newProductFormId)
    {
        reparentFiles(oldProductFormId,newProductFormId);
        List<Attachment> lstPolicyFormAttachments = DAL_Attachment.getAttachmentsByParentIds(new List<Id>{oldProductFormId});
        List<ContentVersion> lstContentVersion = new List<ContentVersion>();
        List<ContentDocumentLink> lstContentDocument = new List<ContentDocumentLink>();
        Set<Id> setAttachmentsToDelete = new Set<Id>();
        System.debug('--Attachment--' + lstPolicyFormAttachments.size());
        if(lstPolicyFormAttachments!=null && !lstPolicyFormAttachments.isEmpty())
        {
            for(Attachment attach : lstPolicyFormAttachments)
            {
                //Insert ContentVersion
                ContentVersion cVersion = new ContentVersion();
                cVersion.ContentLocation = 'S'; //S-Document is in Salesforce. E-Document is outside of Salesforce. L-Document is on a Social Netork.
                cVersion.PathOnClient = attach.Name;//File name with extention
                cVersion.Origin = 'H';//C-Content Origin. H-Chatter Origin.
                cVersion.OwnerId = attach.OwnerId;//Owner of the file
                cVersion.Title = attach.Name;//Name of the file
                cVersion.VersionData = attach.Body;//File content
                lstContentVersion.add(cVersion);
                setAttachmentsToDelete.add(attach.Id);
            }

            insert lstContentVersion;
           
            //query ContentDocumentId for each lstContentVersion
            List<ContentVersion> lstContentVersionForDocId = new List<ContentVersion>();
            lstContentVersionForDocId = [Select ContentDocumentId FROM ContentVersion where ID IN:lstContentVersion];
            for(ContentVersion cVersion : lstContentVersionForDocId)
            {
                ContentDocumentLink cDocLink = new ContentDocumentLink();
                cDocLink.ContentDocumentId = cVersion.ContentDocumentId;//Add ContentDocumentId
                cDocLink.LinkedEntityId = newProductFormId;//Add LinkedEntityId with the newly created 
                cDocLink.ShareType = 'I';//V - Viewer permission. C - Collaborator permission. I - Inferred permission.
                cDocLink.Visibility = 'AllUsers';//AllUsers, InternalUsers, SharedUsers
                lstContentDocument.add(cDocLink);
            }
            insert lstContentDocument;
            if(setAttachmentsToDelete!=null && !setAttachmentsToDelete.isEmpty())
            {
                deleteRecords(setAttachmentsToDelete);    
            }
            
        }
        deleteRecords(new Set<Id>{Id.valueOf(oldProductFormId)});
    }
   
   
    private static void deleteRecords(Set<Id> setRecordsToDelete) 
    {
        List<sObject> lstObjToDelete = new List<sObject>();
        if(setRecordsToDelete!=null && !setRecordsToDelete.isEmpty()) 
        {
            for(Id objId : setRecordsToDelete) 
            {
                String ObjectName = UtilityClass.getObjectNameFromId(objId);
                sObject sObj = Schema.getGlobalDescribe().get(ObjectName).newSObject() ;
                sobj.put('Id',objId);
                lstObjToDelete.add(sobj);
            }
        }
        if(lstObjToDelete!=null && !lstObjToDelete.isEmpty())
        {
            delete lstObjToDelete;
        }
    }
    
    private static void reparentFiles(String oldPolicyFormStateId, String newPolicyFormStateId)
    {
        List<ContentDocumentLink> lstContentDocumentLink = 
        DAL_ContentDocumentLink.getContentDocumentLinkByParentID(new List<Id> {Id.valueOf(oldPolicyFormStateId)});
        List<ContentDocumentLink> lstContentDocumentToInsert  = new List<ContentDocumentLink>();
        for(ContentDocumentLink link : lstContentDocumentLink)
        {
            ContentDocumentLink newLink = new ContentDocumentLink();
            newLink.LinkedEntityId = newPolicyFormStateId;
            newLink.ContentDocumentId = link.ContentDocumentId;
            newLink.ShareType= 'I';
            lstContentDocumentToInsert.add(newLink);
        }
        insert lstContentDocumentToInsert;
    }
   
    private void cloneProductStateStatuses(String message)
    {
        //Get newly created records and existing ones
        List<State_Availability__c> lstProductStates = DAL_ProductState.getProductStatesWithChild(new Set<String>{message,recordId});
        Map<String,State_Availability__c> mapProductStatesOriginal = new Map<String,State_Availability__c>();
        Map<String,State_Availability__c> mapProductStatesCloned = new Map<String,State_Availability__c>();
        if(lstProductStates!=null && !lstProductStates.isEmpty()) {
            for(State_Availability__c prodState : lstProductStates) {
                //cloned map
                if(prodState.Product_Specification__c==message) {
                    mapProductStatesCloned.put(prodState.State__c,prodState);
                }
                if(prodState.Product_Specification__c==recordId) {
                    mapProductStatesOriginal.put(prodState.State__c,prodState);
                }

            }
            
            //loop through the original map and add values from cloned map
            List<Product_State_Status__c> lstProductStateStatusToInsert = new List<Product_State_Status__c>();
            for(State_Availability__c prodStateCloned: mapProductStatesCloned.values()) {
                State_Availability__c prodStateOriginal = mapProductStatesOriginal.get(prodStateCloned.State__c);
                for(Product_State_Status__c prodStateStatusOrginal : prodStateOriginal.Product_State_Statuses__r) {
                    Product_State_Status__c prodStateStatusCloning = new Product_State_Status__c();
                    prodStateStatusCloning.Filing_Status__c = prodStateStatusOrginal.Filing_Status__c;
                    prodStateStatusCloning.Policy_Form_Status__c = prodStateStatusOrginal.Policy_Form_Status__c;
                    prodStateStatusCloning.Product_State_Availability__c = prodStateCloned.Id;
                    lstProductStateStatusToInsert.add(prodStateStatusCloning);
                }
            }
            
        try{
            BaseTriggerHandler.bypass('PRODUCTSPECIFICATIONHANDLER');
            Database.SaveResult[] srList = Database.insert(lstProductStateStatusToInsert,true);
            BaseTriggerHandler.clearBypass('PRODUCTSPECIFICATIONHANDLER');
            // Iterate through each returned result
			for (Database.SaveResult sr : srList) {
			    if (sr.isSuccess()) {
			        // Operation was successful, so get the ID of the record that was processed
			        System.debug('Successfully inserted record ID: ' + sr.getId());
			    }
			    else {
			        // Operation failed, so get all errors                
			        for(Database.Error err : sr.getErrors()) {
			            System.debug('The following error has occurred.');                    
			            System.debug(err.getStatusCode() + ': ' + err.getMessage());
			            System.debug('fields that affected this error: ' + err.getFields());
			        }
			    }
            //insert lstProductStateStatusToInsert;
          }
         } catch(Exception ex) {
          System.debug('Error occured ' + ex.getMessage());
        }
      }
    } 
    
    
    public class ChildObjectWrapper {
        
        public String objName {get;set;}
        public Boolean isSelected {get;set;}   
        public String recordId {get;set;}	
        public String relationshipName {get;set;}
        
        
        ChildObjectWrapper(String objName,Boolean isSelected, String recordId, String relationshipName){
            this.objName = objName;
            this.isSelected = isSelected;
            this.recordId = recordId;
            this.relationshipName = relationshipName;
        }
        
    }
}