F&GDEV/src/objects/Filing_Status__c.object
<CustomObject>
    <description>Object utilized for Product Development efforts</description>
    <fields>
        <fullName>Filing_Status__c</fullName>
        <label>Filing Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Pending Act Support</fullName>
                </value>
                <value>
                    <fullName>Filed</fullName>
                </value>
                <value>
                    <fullName>Objection</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Not Filing</fullName>
                </value>
                <value>
                    <fullName>Pending Compact</fullName>
                </value>
                <value>
                    <fullName>Pending Group</fullName>
                </value>
                <value>
                    <fullName>Approved - Dependent Group</fullName>
                </value>
                <value>
                    <fullName>Approved - Compact</fullName>
                </value>
                <value>
                    <fullName>Approved - Exempt</fullName>
                </value>
                <value>
                    <fullName>Approved - Dependent Compact</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Filed with DOI</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Targeted</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Policy_Form__c</fullName>
        <label>Policy Form</label>
        <referenceTo>Policy_Form_Detail__c</referenceTo>
        <relationshipLabel>Policy Form States</relationshipLabel>
        <relationshipName>Filing_Statuses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>NE</fullName>
                </value>
                <value>
                    <fullName>NV</fullName>
                </value>
                <value>
                    <fullName>NH</fullName>
                </value>
                <value>
                    <fullName>NJ</fullName>
                </value>
                <value>
                    <fullName>NM</fullName>
                </value>
                <value>
                    <fullName>NY</fullName>
                </value>
                <value>
                    <fullName>NC</fullName>
                </value>
                <value>
                    <fullName>ND</fullName>
                </value>
                <value>
                    <fullName>OH</fullName>
                </value>
                <value>
                    <fullName>OK</fullName>
                </value>
                <value>
                    <fullName>OR</fullName>
                </value>
                <value>
                    <fullName>PA</fullName>
                </value>
                <value>
                    <fullName>RI</fullName>
                </value>
                <value>
                    <fullName>SC</fullName>
                </value>
                <value>
                    <fullName>SD</fullName>
                </value>
                <value>
                    <fullName>TN</fullName>
                </value>
                <value>
                    <fullName>TX</fullName>
                </value>
                <value>
                    <fullName>UT</fullName>
                </value>
                <value>
                    <fullName>VT</fullName>
                </value>
                <value>
                    <fullName>VA</fullName>
                </value>
                <value>
                    <fullName>WA</fullName>
                </value>
                <value>
                    <fullName>WV</fullName>
                </value>
                <value>
                    <fullName>WI</fullName>
                </value>
                <value>
                    <fullName>WY</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Policy Form State</label>
    <nameField>
        <label>Policy Form State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Form States</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

F&GDEV/src/objects/Product_State_Status__c.object
<CustomObject>
    <description>Value set via trigger, to match the filing status on the related Policy Form State record, so that it can be used in a roll-up summary field on the Product State record.</description>
    <fields>
        <fullName>Filing_Status__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Policy Form State</label>
        <referenceTo>Filing_Status__c</referenceTo>
        <relationshipLabel>Product State Policy Form Associations</relationshipLabel>
        <relationshipName>Product_State_Statuses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product State Policy Form Association</label>
    <nameField>
        <displayFormat>PSPF - {0000}</displayFormat>
        <label>Product State Policy Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product State Policy Form Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

F&GDEV/src/objects/State_Availability__c.object
<CustomObject>
    <description>Object utilized for Product Development efforts</description>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>NC</fullName>
                </value>
                <value>
                    <fullName>ND</fullName>
                </value>
                <value>
                    <fullName>NE</fullName>
                </value>
                <value>
                    <fullName>NH</fullName>
                </value>
                <value>
                    <fullName>NJ</fullName>
                </value>
                <value>
                    <fullName>NM</fullName>
                </value>
                <value>
                    <fullName>NV</fullName>
                </value>
                <value>
                    <fullName>NY</fullName>
                </value>
                <value>
                    <fullName>OH</fullName>
                </value>
                <value>
                    <fullName>OK</fullName>
                </value>
                <value>
                    <fullName>OR</fullName>
                </value>
                <value>
                    <fullName>PA</fullName>
                </value>
                <value>
                    <fullName>RI</fullName>
                </value>
                <value>
                    <fullName>SC</fullName>
                </value>
                <value>
                    <fullName>SD</fullName>
                </value>
                <value>
                    <fullName>TN</fullName>
                </value>
                <value>
                    <fullName>TX</fullName>
                </value>
                <value>
                    <fullName>UT</fullName>
                </value>
                <value>
                    <fullName>VA</fullName>
                </value>
                <value>
                    <fullName>VT</fullName>
                </value>
                <value>
                    <fullName>WA</fullName>
                </value>
                <value>
                    <fullName>WI</fullName>
                </value>
                <value>
                    <fullName>WV</fullName>
                </value>
                <value>
                    <fullName>WY</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Product State</label>
    <nameField>
        <label>Product State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product States</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

F&GDEV/src/classes/ProductStatePolicyAssocHandlerTest.cls
@isTest
private class ProductStatePolicyAssocHandlerTest {
	
	@isTest static void AssociateStatusTest() {
		initStateRecs();

		//	Create Policies
		List<String> TestStateList = new List<String>{'AL', 'LA', 'ID', 'WY', 'FL'};

		List<Policy_Form_Detail__c> policyformList = (List<Policy_Form_Detail__c>)SmartFactory.createSObjectList('Policy_Form_Detail__c', false, 5);
		Integer i = 0;
		for(Policy_Form_Detail__c policyform : policyformList){
			policyform.Name = 'Policy Spec Name ' + i;
			i += 1;
		}
		insert policyformList;

		Map<Id, Policy_Form_Detail__c> policyformMap = new Map<Id, Policy_Form_Detail__c>([Select Id, Name from Policy_Form_Detail__c]);

		//	Create Filing Status
		List<Filing_Status__c> filingstatList = new List<Filing_Status__c>();
		Integer j = 0;
		for(String statecode : TestStateList){
			for(Policy_Form_Detail__c policyform : policyformList){
				filingstatList.add(new Filing_Status__c(Policy_Form__c = policyform.Id, State__c = statecode, Filing_Status__c = 'In Progress'));
				j += 1;
			}
		}
		insert filingstatList;
		Map<Id, Filing_Status__c> filingStatMap = new Map<Id, Filing_Status__c>(filingstatList);

		//	Create Products
		List<Product_Specification__c> prodspecList = (List<Product_Specification__c>)SmartFactory.createSObjectList('Product_Specification__c', false, 2);
		Integer k = 0;
		for(Product_Specification__c prodspec : prodspecList){
			prodspec.Name = 'Prod Spec Name ' + k;
			k += 1;
		}
		insert prodspecList;

		List<State_Availability__c> stateavailList = new List<State_Availability__c>([Select Id from State_Availability__c]);
		//	List<Filing_Status__c> filingstatList = new List<Filing_Status__c>([Select Id from Filing_Status__c]);

		//	Create Product State Policies
		List<Product_State_Status__c> prodstatestatList = new List<Product_State_Status__c>();

		for(State_Availability__c stateavail : stateavailList){
			for(Filing_Status__c filingstat : filingstatList){
				prodstatestatList.add(new Product_State_Status__c(Filing_Status__c = filingstat.Id, Product_State_Availability__c = stateavail.Id));
			}
		}
		insert prodstatestatList;

		//	Validate Statuses Have Been Copied
		for(Product_State_Status__c prdstatestat : [Select Filing_Status__c, Policy_Form_Status__c from Product_State_Status__c]){
			System.assertEquals(filingStatMap.get(prdstatestat.Filing_Status__c).Filing_Status__c, prdstatestat.Policy_Form_Status__c);
		}

		// Batch Create Product Specs

	}
	
	private static void initStateRecs(){
		List<State__c> stateavailList = new List<State__c>();
		stateavailList.add(new State__c(Name='Alaska',StateCode__c = 'AK'));
		stateavailList.add(new State__c(Name='Alabama',StateCode__c = 'AL'));
		stateavailList.add(new State__c(Name='Arkansas',StateCode__c = 'AR'));
		stateavailList.add(new State__c(Name='Arizona',StateCode__c = 'AZ'));
		stateavailList.add(new State__c(Name='California',StateCode__c = 'CA'));
		stateavailList.add(new State__c(Name='Colorado',StateCode__c = 'CO'));
		stateavailList.add(new State__c(Name='Connecticut',StateCode__c = 'CT'));
		stateavailList.add(new State__c(Name='District of Columbia',StateCode__c = 'DC'));
		stateavailList.add(new State__c(Name='Delaware',StateCode__c = 'DE'));
		stateavailList.add(new State__c(Name='Florida',StateCode__c = 'FL'));
		stateavailList.add(new State__c(Name='Georgia',StateCode__c = 'GA'));
		stateavailList.add(new State__c(Name='Hawaii',StateCode__c = 'HI'));
		stateavailList.add(new State__c(Name='Iowa',StateCode__c = 'IA'));
		stateavailList.add(new State__c(Name='Idaho',StateCode__c = 'ID'));
		stateavailList.add(new State__c(Name='Illinois',StateCode__c = 'IL'));
		stateavailList.add(new State__c(Name='Indiana',StateCode__c = 'IN'));
		stateavailList.add(new State__c(Name='Kansas',StateCode__c = 'KS'));
		stateavailList.add(new State__c(Name='Kentucky',StateCode__c = 'KY'));
		stateavailList.add(new State__c(Name='Louisiana',StateCode__c = 'LA'));
		stateavailList.add(new State__c(Name='Massachusetts',StateCode__c = 'MA'));
		stateavailList.add(new State__c(Name='Maryland',StateCode__c = 'MD'));
		stateavailList.add(new State__c(Name='Maine',StateCode__c = 'ME'));
		stateavailList.add(new State__c(Name='Michigan',StateCode__c = 'MI'));
		stateavailList.add(new State__c(Name='Minnesota',StateCode__c = 'MN'));
		stateavailList.add(new State__c(Name='Missouri',StateCode__c = 'MO'));
		stateavailList.add(new State__c(Name='Mississippi',StateCode__c = 'MS'));
		stateavailList.add(new State__c(Name='Montana',StateCode__c = 'MT'));
		stateavailList.add(new State__c(Name='North Carolina',StateCode__c = 'NC'));
		stateavailList.add(new State__c(Name='North Dakota',StateCode__c = 'ND'));
		stateavailList.add(new State__c(Name='Nebraska',StateCode__c = 'NE'));
		stateavailList.add(new State__c(Name='New Hampshire',StateCode__c = 'NH'));
		stateavailList.add(new State__c(Name='New Jersey',StateCode__c = 'NJ'));
		stateavailList.add(new State__c(Name='New Mexico',StateCode__c = 'NM'));
		stateavailList.add(new State__c(Name='Nevada',StateCode__c = 'NV'));
		stateavailList.add(new State__c(Name='New York',StateCode__c = 'NY'));
		stateavailList.add(new State__c(Name='Ohio',StateCode__c = 'OH'));
		stateavailList.add(new State__c(Name='Oklahoma',StateCode__c = 'OK'));
		stateavailList.add(new State__c(Name='Oregon',StateCode__c = 'OR'));
		stateavailList.add(new State__c(Name='Pennsylvania',StateCode__c = 'PA'));
		stateavailList.add(new State__c(Name='Rhode Island',StateCode__c = 'RI'));
		stateavailList.add(new State__c(Name='South Carolina',StateCode__c = 'SC'));
		stateavailList.add(new State__c(Name='South Dakota',StateCode__c = 'SD'));
		stateavailList.add(new State__c(Name='Tennessee',StateCode__c = 'TN'));
		stateavailList.add(new State__c(Name='Texas',StateCode__c = 'TX'));
		stateavailList.add(new State__c(Name='Utah',StateCode__c = 'UT'));
		stateavailList.add(new State__c(Name='Virginia',StateCode__c = 'VA'));
		stateavailList.add(new State__c(Name='Vermont',StateCode__c = 'VT'));
		stateavailList.add(new State__c(Name='Washington',StateCode__c = 'WA'));
		stateavailList.add(new State__c(Name='Wisconsin',StateCode__c = 'WI'));
		stateavailList.add(new State__c(Name='West Virginia',StateCode__c = 'WV'));
		stateavailList.add(new State__c(Name='Wyoming',StateCode__c = 'WY'));


		insert stateavailList;
	}	

}