F&GDEV/src/objects/Filing_Status__c.object
<CustomObject>
    <description>Object utilized for Product Development efforts</description>
    <fields>
        <fullName>File_Date_To_Vendor__c</fullName>
        <label>File Date (To Vendor)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Filing_Followup_Date__c</fullName>
        <label>Filing Followup Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Filing_Status__c</fullName>
        <label>Filing Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Pending Act Support</fullName>
                </value>
                <value>
                    <fullName>Filed</fullName>
                </value>
                <value>
                    <fullName>Objection</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Not Filing</fullName>
                </value>
                <value>
                    <fullName>Pending Compact</fullName>
                </value>
                <value>
                    <fullName>Pending Group</fullName>
                </value>
                <value>
                    <fullName>Approved - Dependent Group</fullName>
                </value>
                <value>
                    <fullName>Approved - Compact</fullName>
                </value>
                <value>
                    <fullName>Approved - Exempt</fullName>
                </value>
                <value>
                    <fullName>Approved - Dependent Compact</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Filed with DOI</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Targeted</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Filing_Withdrawn_Date__c</fullName>
        <label>Filing Withdrawn Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Most_Recent_Objection_Response_Date__c</fullName>
        <label>Most Recent Objection Response Date</label>
        <summarizedField>Filing_Objection__c.Objection_Received__c</summarizedField>
        <summaryForeignKey>Filing_Objection__c.Policy_Form_State__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Objection_Deadline_Date__c</fullName>
        <label>Current Objection Deadline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Objection_Received_Date__c</fullName>
        <label>Objection Received Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Objection_Response_Date__c</fullName>
        <label>Most Recent Objection Response Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>State_Approval_Date__c</fullName>
        <inlineHelpText>This should be completed if Exempt or Approved.</inlineHelpText>
        <label>State Approval Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Submitted_to_State_Date__c</fullName>
        <label>Submitted to State Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Target_File_Date__c</fullName>
        <label>Target File Date</label>
        <type>Date</type>
    </fields>
    <label>Policy Form State</label>
    <nameField>
        <label>Policy Form State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Form States</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

F&GDEV/src/objects/Policy_Form_Detail__c.object
<CustomObject>
    <description>Object utilized for Product Development efforts</description>
    <fields>
        <fullName>Policy_Form_Name__c</fullName>
        <label>Policy Form Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Policy_Form_Type__c</fullName>
        <label>Policy Form Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Base Policy Form</fullName>
                </value>
                <value>
                    <fullName>Rider Policy Form</fullName>
                </value>
                <value>
                    <fullName>Application</fullName>
                </value>
                <value>
                    <fullName>Endorsement</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The status field describes whether state approvals have been provided or if the filing is still active and has not received state approvals.</description>
        <inlineHelpText>Whether state approvals have been provided or if the filing is still active and has not received state approvals.</inlineHelpText>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Policy Form</label>
    <nameField>
        <label>Policy Form</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Forms</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

F&GDEV/src/classes/W_Policy.cls
global with sharing class W_Policy 
{
	global W_Policy(Policy_Form_Detail__c policy, Filing_Status__c filingstatus)
	 {
		this(policy);
		this.Status = filingstatus.Filing_Status__c;

		//	Calculate and Set Date
		if(this.Status == 'Filed'){
			if(filingstatus.File_Date_To_Vendor__c != null){
				this.StatusDate = filingstatus.File_Date_To_Vendor__c.format();
			}else if (filingstatus.Filing_Followup_Date__c != null){
				this.StatusDate = filingstatus.Filing_Followup_Date__c.format();
			}
            //Label : Submitted to State Date field
            else if(filingstatus.Submitted_to_State_Date__c != null){
				this.StatusDate = filingstatus.Submitted_to_State_Date__c.format();
			}
		}else if (this.Status == 'Approved'){
			if(filingstatus.State_Approval_Date__c != null){
				this.StatusDate = filingstatus.State_Approval_Date__c.format();
			}
		}else if (this.Status == 'Objection'){
			if(filingstatus.Objection_Deadline_Date__c != null){
				this.StatusDate = filingstatus.Objection_Deadline_Date__c.format();
			}else if (filingstatus.Objection_Received_Date__c != null){
				this.StatusDate = filingstatus.Objection_Received_Date__c.format();
			}else if (filingstatus.Objection_Response_Date__c != null){
				this.StatusDate = filingstatus.Objection_Response_Date__c.format();
            }
            //Rollup field from Filing Objection object
            else if(filingstatus.Most_Recent_Objection_Response_Date__c != null){
                this.StatusDate = filingstatus.Most_Recent_Objection_Response_Date__c.format();
            }

		}else if (this.Status == 'Targeted'){
			if(filingstatus.Target_File_Date__c != null){
				this.StatusDate = filingstatus.Target_File_Date__c.format();
			}

		}else if (this.Status == 'Withdrawn'){
			if(filingstatus.Filing_Withdrawn_Date__c != null){
				this.StatusDate = filingstatus.Filing_Withdrawn_Date__c.format();
			}

		}	

		this.FilingStatusId = filingstatus.Id;
		this.FilingStatusObj = filingstatus;
	}

	global W_Policy(Policy_Form_Detail__c policy) {
		this.Id = policy.Id;
		this.Name = policy.Name;
		this.FormName = policy.Policy_Form_Name__c;	
        this.PolicyFormType = policy.Policy_Form_Type__c;
        this.PolicyFormStatus = policy.Status__c;
		this.UISelected = false;
	}

	//	public Policy_Form_Detail__c PolicyInstance{get{return pvtPolicy;}}
	global Id Id{get; set;}
	global Id FilingStatusId {get; set;}
	global Id FilingStatusAvailId {get; set;}
	
	global String Name {get; set;}
	global String FormName {get; set;}
	global String Status {get; set;}
	global String StatusDate {get; set;}

	global Boolean UISelected{get; set;}
    global String PolicyFormType{get;set;}
    global String PolicyFormStatus{get;set;}
	global Filing_Status__c FilingStatusObj {get; set;}
     

}