F&GDEV/src/objects/Filing_Status__c.object
<CustomObject>
    <description>Object utilized for Product Development efforts</description>
    <fields>
        <fullName>Filing_Status__c</fullName>
        <label>Filing Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Pending Act Support</fullName>
                </value>
                <value>
                    <fullName>Filed</fullName>
                </value>
                <value>
                    <fullName>Objection</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Not Filing</fullName>
                </value>
                <value>
                    <fullName>Pending Compact</fullName>
                </value>
                <value>
                    <fullName>Pending Group</fullName>
                </value>
                <value>
                    <fullName>Approved - Dependent Group</fullName>
                </value>
                <value>
                    <fullName>Approved - Compact</fullName>
                </value>
                <value>
                    <fullName>Approved - Exempt</fullName>
                </value>
                <value>
                    <fullName>Approved - Dependent Compact</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Filed with DOI</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Targeted</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Policy_Form__c</fullName>
        <label>Policy Form</label>
        <referenceTo>Policy_Form_Detail__c</referenceTo>
        <relationshipLabel>Policy Form States</relationshipLabel>
        <relationshipName>Filing_Statuses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>NE</fullName>
                </value>
                <value>
                    <fullName>NV</fullName>
                </value>
                <value>
                    <fullName>NH</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Policy Form State</label>
    <nameField>
        <label>Policy Form State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Form States</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

F&GDEV/src/objects/Policy_Form_Detail__c.object
<CustomObject>
    <description>Object utilized for Product Development efforts</description>
    <fields>
        <fullName>Policy_Form_State__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Policy Form State</label>
        <referenceTo>Filing_Status__c</referenceTo>
        <relationshipLabel>Policy Forms</relationshipLabel>
        <relationshipName>Policy_Form</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Policy Form</label>
    <nameField>
        <label>Policy Form</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Forms</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

F&GDEV/src/objects/Product_Specification__c.object
<CustomObject>
    <description>Object utilized for Product Development efforts</description>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

F&GDEV/src/objects/Product_State_Status__c.object
<CustomObject>
    <description>Value set via trigger, to match the filing status on the related Policy Form State record, so that it can be used in a roll-up summary field on the Product State record.</description>
    <fields>
        <fullName>Filing_Status__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Policy Form State</label>
        <referenceTo>Filing_Status__c</referenceTo>
        <relationshipLabel>Product State Policy Form Associations</relationshipLabel>
        <relationshipName>Product_State_Statuses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_State_Availability__c</fullName>
        <label>Product State</label>
        <referenceTo>State_Availability__c</referenceTo>
        <relationshipLabel>Product State Policy Form Associations</relationshipLabel>
        <relationshipName>Product_State_Statuses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Product State Policy Form Association</label>
    <nameField>
        <displayFormat>PSPF - {0000}</displayFormat>
        <label>Product State Policy Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product State Policy Form Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

F&GDEV/src/objects/State__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List of supported policy states.</description>
    <label>State</label>
</CustomObject>

F&GDEV/src/objects/State_Availability__c.object
<CustomObject>
    <description>Object utilized for Product Development efforts</description>
    <fields>
        <fullName>Product_Specification__c</fullName>
        <label>Product Specification</label>
        <referenceTo>Product_Specification__c</referenceTo>
        <relationshipName>Product_State_Availabilities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>NC</fullName>
                </value>
                <value>
                    <fullName>ND</fullName>
                </value>
                <value>
                    <fullName>NE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Product State</label>
    <nameField>
        <label>Product State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product States</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

F&GDEV/src/classes/DAL_ProductStateStatus.cls
public class DAL_ProductStateStatus {
    
    public static List<Product_State_Status__c> getProductStatusByIds(Set<Id> lstProductStatusIds) 
    {
        return [
                Select 
                Id, 
                Product_State_Availability__r.State__c, 
                Product_State_Availability__r.Product_Specification__r.Name,
                Filing_Status__r.Policy_Form__r.Name 
                from Product_State_Status__c where 
                Id 
                IN: lstProductStatusIds
                Order by 
                Product_State_Availability__r.State__c
                ];
    }
    
    public static List<Product_State_Status__c> getProductStatusByParent(Set<Id> setPolicyForm, Set<ID> setProductState)
    {
        return [
                Select 
                Id, 
                Product_State_Availability__c, 
                Filing_Status__c 
                from 
                Product_State_Status__c
                Where 
                Filing_Status__c IN:setPolicyForm 
                OR 
                Product_State_Availability__c IN:setProductState
                ];
    }

}