F&GDEV/src/objects/Filing_Status__c.object
<CustomObject>
    <description>Object utilized for Product Development efforts</description>
    <fields>
        <fullName>File_Date_To_Vendor__c</fullName>
        <label>File Date (To Vendor)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Filing_Followup_Date__c</fullName>
        <label>Filing Followup Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Filing_Notes_Status_Notes__c</fullName>
        <inlineHelpText>Provide high-level comments for reporting purposes and for stakeholders to view quickly.</inlineHelpText>
        <label>Filing Notes Summary</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Filing_Notes__c</fullName>
        <inlineHelpText>Provide detailed filing notes for internal purposes. This field provides additional information that may not be necessary to view in exported reports.</inlineHelpText>
        <label>Filing Notes Detail</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Filing_Status__c</fullName>
        <label>Filing Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Pending Act Support</fullName>
                </value>
                <value>
                    <fullName>Filed</fullName>
                </value>
                <value>
                    <fullName>Objection</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Not Filing</fullName>
                </value>
                <value>
                    <fullName>Pending Compact</fullName>
                </value>
                <value>
                    <fullName>Pending Group</fullName>
                </value>
                <value>
                    <fullName>Approved - Dependent Group</fullName>
                </value>
                <value>
                    <fullName>Approved - Compact</fullName>
                </value>
                <value>
                    <fullName>Approved - Exempt</fullName>
                </value>
                <value>
                    <fullName>Approved - Dependent Compact</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Filed with DOI</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Targeted</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Filing_Withdrawn_Date__c</fullName>
        <label>Filing Withdrawn Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Most_Recent_Objection_Response_Date__c</fullName>
        <label>Most Recent Objection Response Date</label>
        <summarizedField>Filing_Objection__c.Objection_Received__c</summarizedField>
        <summaryForeignKey>Filing_Objection__c.Policy_Form_State__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Objection_Deadline_Date__c</fullName>
        <label>Current Objection Deadline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Objection_Received_Date__c</fullName>
        <label>Objection Received Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Objection_Response_Date__c</fullName>
        <label>Most Recent Objection Response Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Policy_Form__c</fullName>
        <label>Policy Form</label>
        <referenceTo>Policy_Form_Detail__c</referenceTo>
        <relationshipLabel>Policy Form States</relationshipLabel>
        <relationshipName>Filing_Statuses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>State_Approval_Date__c</fullName>
        <inlineHelpText>This should be completed if Exempt or Approved.</inlineHelpText>
        <label>State Approval Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>NE</fullName>
                </value>
                <value>
                    <fullName>NV</fullName>
                </value>
                <value>
                    <fullName>NH</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Submitted_to_State_Date__c</fullName>
        <label>Submitted to State Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Target_File_Date__c</fullName>
        <label>Target File Date</label>
        <type>Date</type>
    </fields>
    <label>Policy Form State</label>
    <nameField>
        <label>Policy Form State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Form States</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

F&GDEV/src/objects/Policy_Form_Detail__c.object
<CustomObject>
    <description>Object utilized for Product Development efforts</description>
    <fields>
        <fullName>Approved_States__c</fullName>
        <label>Approved States</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Policy_Form_Name__c</fullName>
        <label>Policy Form Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Policy_Form_Type__c</fullName>
        <label>Policy Form Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Base Policy Form</fullName>
                </value>
                <value>
                    <fullName>Rider Policy Form</fullName>
                </value>
                <value>
                    <fullName>Application</fullName>
                </value>
                <value>
                    <fullName>Endorsement</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Policy Forms</relationshipLabel>
        <relationshipName>PolicyForms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The status field describes whether state approvals have been provided or if the filing is still active and has not received state approvals.</description>
        <inlineHelpText>Whether state approvals have been provided or if the filing is still active and has not received state approvals.</inlineHelpText>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Policy Form</label>
    <nameField>
        <label>Policy Form</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Forms</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

F&GDEV/src/objects/Project__c.object
<CustomObject>
    <description>Object utilized for Product Development efforts</description>
    <fields>
        <fullName>Filing_Status__c</fullName>
        <label>Filing Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No Filing Required</fullName>
                </value>
                <value>
                    <fullName>Filing Required</fullName>
                </value>
                <value>
                    <fullName>Filing In Progress</fullName>
                </value>
                <value>
                    <fullName>Filing Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

F&GDEV/src/objects/State__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List of supported policy states.</description>
    <label>State</label>
</CustomObject>

F&GDEV/src/classes/DAL_PolicyFormDetail.cls
public with sharing class DAL_PolicyFormDetail {
	
	public static List<Policy_Form_Detail__c> getByIds(List<Id> ids)
	{
		return [Select 
					   id,
					   Name,
					   Approved_States__c
			      FROM 
			      	  Policy_Form_Detail__c
			    WHERE 
			    	 Id IN:ids];
	}	
    
    
    public static List<Policy_Form_Detail__c> getByName(String formName)
	{
		return [SELECT 
						Id,
						Name,
						createddate
			       FROM 
			       		Policy_Form_Detail__c
			      WHERE 
			           Name=:formName 
			     ORDER by createddate desc];
	}	
	
	public static List<Policy_Form_Detail__c> getByPolicyFormDetailIds(List<Id> policyIds)
	{
		return [Select Id, 
					   Name,
					   Policy_Form_Name__c,
					   Project__c,
               		   Status__c, 
                       Policy_Form_Type__c,
	                   (Select
	                   		  Id,
                              State__c, 
	                    	  Filing_Status__c, 
	                   		  File_Date_To_Vendor__c, 
	                  		  Filing_Followup_Date__c,
	                   		  State_Approval_Date__c, 
	                   		  Submitted_to_State_Date__c, 
	                   		  Objection_Deadline_Date__c,
	                    	  Objection_Received_Date__c,
	                          Objection_Response_Date__c,
                        	  Most_Recent_Objection_Response_Date__c,
	                          Target_File_Date__c, 
	                    	  Filing_Withdrawn_Date__c,
	                  		  Filing_Notes__c, 
	                  		  Filing_Notes_Status_Notes__c 
	                     FROM 
	                     	  Filing_Statuses__r) 
                   FROM 
                        Policy_Form_Detail__c
                  WHERE
                        Id in: policyIds];
	}
}