F&GDEV/src/objects/Filing_Status__c.object
<CustomObject>
    <description>Object utilized for Product Development efforts</description>
    <fields>
        <fullName>Filing_Status__c</fullName>
        <label>Filing Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Pending Act Support</fullName>
                </value>
                <value>
                    <fullName>Filed</fullName>
                </value>
                <value>
                    <fullName>Objection</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Not Filing</fullName>
                </value>
                <value>
                    <fullName>Pending Compact</fullName>
                </value>
                <value>
                    <fullName>Pending Group</fullName>
                </value>
                <value>
                    <fullName>Approved - Dependent Group</fullName>
                </value>
                <value>
                    <fullName>Approved - Compact</fullName>
                </value>
                <value>
                    <fullName>Approved - Exempt</fullName>
                </value>
                <value>
                    <fullName>Approved - Dependent Compact</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Filed with DOI</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Targeted</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Policy Form State</label>
    <nameField>
        <label>Policy Form State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Form States</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

F&GDEV/src/objects/Product_State_Status__c.object
<CustomObject>
    <description>Value set via trigger, to match the filing status on the related Policy Form State record, so that it can be used in a roll-up summary field on the Product State record.</description>
    <fields>
        <fullName>Filing_Status__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Policy Form State</label>
        <referenceTo>Filing_Status__c</referenceTo>
        <relationshipLabel>Product State Policy Form Associations</relationshipLabel>
        <relationshipName>Product_State_Statuses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_State_Availability__c</fullName>
        <label>Product State</label>
        <referenceTo>State_Availability__c</referenceTo>
        <relationshipLabel>Product State Policy Form Associations</relationshipLabel>
        <relationshipName>Product_State_Statuses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Product State Policy Form Association</label>
    <nameField>
        <displayFormat>PSPF - {0000}</displayFormat>
        <label>Product State Policy Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product State Policy Form Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

F&GDEV/src/classes/DAL_ProductStatePolicyFormAssociation.cls
public with sharing class DAL_ProductStatePolicyFormAssociation
{
	
	public static List<Product_State_Status__c> getByFilingStatusIds(List<Id> fillingStatusIds)
	{
		return [SELECT 
					   Id,
					   Name,
					   Filing_Status__c
				  FROM
				  		Product_State_Status__c
				  WHERE 
				  	    Filing_Status__c IN: fillingStatusIds];
	}
	
	
	public static List<Product_State_Status__c> getByProductStateAvailabilityIds(List<Id> productStateAvailabilityIds)
	{
		return [SELECT
						ID,
						Filing_Status__c,
						Product_State_Availability__c
				    FROM
				        Product_State_Status__c
				     WHERE
				         Product_State_Availability__c IN:productStateAvailabilityIds];
	}
	
	
	public static Map<Id,Product_State_Status__c> getByfillingStatusMap(List<Id> fillingStatusIds)
	{
		Map<Id,Product_State_Status__c> fillinstatusIdProductStateStatusMap = new Map<Id,Product_State_Status__c>();
		
		for(Product_State_Status__c pd:getByFilingStatusIds(fillingStatusIds))
		{
			fillinstatusIdProductStateStatusMap.put(pd.Filing_Status__c,pd);
		}
		
		return fillinstatusIdProductStateStatusMap;
	}
	
	
	public static Map<Id,Product_State_Status__c> getByProductStateAvailabilityIdsMap(List<Id> productStateAvailabilityIds)
	{
		Map<Id,Product_State_Status__c> productStateAvailabilityIdProductStatus  = new Map<Id,Product_State_Status__c>();
		for(Product_State_Status__c pstate:getByProductStateAvailabilityIds(productStateAvailabilityIds))
		{
			productStateAvailabilityIdProductStatus.put(pstate.Product_State_Availability__c,pstate);
		}	
		
		return productStateAvailabilityIdProductStatus;			         
	}
	
    
}