F&GDEV/src/objects/Marketing_Materials__c.object
<CustomObject>
    <description>Object utilized for Product Development efforts</description>
    <fields>
        <fullName>Mkt_Form_Prefix__c</fullName>
        <label>Mkt Form Prefix</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ADLF</fullName>
                </value>
                <value>
                    <fullName>ADMIN</fullName>
                </value>
                <value>
                    <fullName>ADTJ</fullName>
                </value>
                <value>
                    <fullName>ADV</fullName>
                </value>
                <value>
                    <fullName>FG</fullName>
                </value>
                <value>
                    <fullName>LMG</fullName>
                </value>
                <value>
                    <fullName>NYCO</fullName>
                </value>
                <value>
                    <fullName>OM</fullName>
                </value>
                <value>
                    <fullName>OMCO</fullName>
                </value>
                <value>
                    <fullName>PORT</fullName>
                </value>
                <value>
                    <fullName>AAPP</fullName>
                </value>
                <value>
                    <fullName>LAPP</fullName>
                </value>
                <value>
                    <fullName>NYAD</fullName>
                </value>
                <value>
                    <fullName>FGNY</fullName>
                </value>
                <value>
                    <fullName>ICC11</fullName>
                </value>
                <value>
                    <fullName>ICC14</fullName>
                </value>
                <value>
                    <fullName>ICC15</fullName>
                </value>
                <value>
                    <fullName>ICC18</fullName>
                </value>
                <value>
                    <fullName>OMAD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Request_Ad_Review_No__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Request Ad Review No</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Request_MM_No__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Request MM No.</label>
        <type>Checkbox</type>
    </fields>
    <label>Marketing Materials</label>
    <nameField>
        <displayFormat>MM-{0000}</displayFormat>
        <label>Marketing Materials Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Marketing Materials</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

F&GDEV/src/classes/MarketingMaterialsHandler.cls
public with sharing class MarketingMaterialsHandler extends BaseTriggerHandler {
	
	
	private List<Marketing_Materials__c> newMarketingMaterials;
    private List<Marketing_Materials__c> oldMarketingMaterials;
    private Map<ID, Marketing_Materials__c> newMarketingMaterialMap;
    private Map<ID, Marketing_Materials__c> oldMarketingMaterialMap;
	
	public MarketingMaterialsHandler()
    {
        oldMarketingMaterials = (List<Marketing_Materials__c>)Trigger.old;
        newMarketingMaterials = (List<Marketing_Materials__c>)Trigger.new;
        newMarketingMaterialMap = (Map<ID, Marketing_Materials__c>)Trigger.newMap;
        oldMarketingMaterialMap = (Map<ID, Marketing_Materials__c>)Trigger.oldMap;
    }
    
    @TestVisible
    protected override void beforeInsert()
    {
    	if(TriggerCheck.canRun('TH_MARKETINGMATERIALSHANDLER'))
    	{
    		requestAutonumber(Trigger.isBefore, Trigger.isUpdate, Trigger.isInsert, oldMarketingMaterialMap, newMarketingMaterialMap, newMarketingMaterials);
    	}
    }
    
    
    @TestVisible
    protected override void beforeUpdate()
    {
		if(TriggerCheck.canRun('TH_MARKETINGMATERIALSHANDLER'))
    	{
			requestAutonumber(Trigger.isBefore, Trigger.isUpdate, Trigger.isInsert, oldMarketingMaterialMap, newMarketingMaterialMap, newMarketingMaterials);
    	}
    }
	
	public void requestAutonumber(Boolean isBefore, Boolean isUpdate, Boolean isInsert, Map<Id, Marketing_Materials__c> oldMap, Map<Id, Marketing_Materials__c> newMap
		, List<Marketing_Materials__c> newList)
	{
		
		if(isBefore && (isUpdate || isInsert)){
			List<Marketing_Materials__c> adreviewProcList = new List<Marketing_Materials__c>(); 
			Map<String, List<Marketing_Materials__c>> prefixmktgmatsProcListMap = new Map<String, List<Marketing_Materials__c>>(); 


			//	Create List of Records for Processing
			for(Marketing_Materials__c newMktMats : newList){
				Id key = newMktMats.Id;

				//	Capture Records for Retrieve of New ATI Numbers
				if(  (isInsert || (isUpdate && !oldMap.get(key).Request_Ad_Review_No__c)) && newMktMats.Request_Ad_Review_No__c ){
					adreviewProcList.add(newMktMats);			
				}

				//	Capture Prefix for Marketing Materials
				String prefix;
				if(  (isInsert || (isUpdate && !oldMap.get(key).Request_MM_No__c)) && newMktMats.Request_MM_No__c ){
					prefix = newMktMats.Mkt_Form_Prefix__c;
				}

				if(!String.isBlank(prefix)){
					if(!prefixmktgmatsProcListMap.containsKey(prefix)){
						prefixmktgmatsProcListMap.put(prefix, new List<Marketing_Materials__c>());
					}
					prefixmktgmatsProcListMap.get(prefix).add(newMktMats);			
				}

			}

			//	Send to AutoNumber Algo
			AutoNumber.ProcessAdReviewRequests(adreviewProcList);
			AutoNumber.ProcessMktgMatsRequests(prefixmktgmatsProcListMap);
		}

	}
}