F&GDEV/src/objects/Object_clone_skipped_field__mdt.object
<CustomObject>
    <description>This is a generic setting which can be used to skip fields which should not be cloned while an object is being cloned</description>
    <fields>
        <fullName>Field_Name__c</fullName>
        <description>API name of the field to be skipped during the clone</description>
        <label>Field Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object_Name__c</fullName>
        <description>The picklist for the objects for which the fields will be skipped</description>
        <label>Object Name</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>State_Availability__c</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Marketing_Name__c</fullName>
                </value>
                <value>
                    <fullName>Marketing_Materials__c</fullName>
                </value>
                <value>
                    <fullName>Product_State_Status__c</fullName>
                </value>
                <value>
                    <fullName>Product_to_Plan_Code_Association__c</fullName>
                </value>
                <value>
                    <fullName>Marketing_to_Product_State_Association__c</fullName>
                </value>
                <value>
                    <fullName>Product_Specification__c</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Parent_Object_Name__c</fullName>
        <description>Picklist values for the parent object for which the skip is going to happen</description>
        <label>Parent Object Name</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Product_Specification__c</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Marketing_Materials__c</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Object clone skipped field</label>
    <pluralLabel>Object clone skipped fields</pluralLabel>
</CustomObject>

F&GDEV/src/objects/Product_Specification__c.object
<CustomObject>
    <description>Object utilized for Product Development efforts</description>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

F&GDEV/src/objects/State_Availability__c.object
<CustomObject>
    <description>Object utilized for Product Development efforts</description>
    <fields>
        <fullName>Product_Specification__c</fullName>
        <label>Product Specification</label>
        <referenceTo>Product_Specification__c</referenceTo>
        <relationshipName>Product_State_Availabilities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Product State</label>
    <nameField>
        <label>Product State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product States</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

F&GDEV/src/classes/DAL_ObjectCloneSkippedField_T.cls
@isTest
private class DAL_ObjectCloneSkippedField_T {
    public static User admin_User;
    public static Integer count =1;
    public static string SYSTEM_ADMINISTRATOR_PROFILE ='System Administrator';
    public static Object_clone_skipped_field__mdt objectCloneSkippedFields = new Object_clone_skipped_field__mdt();
    
    static void testData()
    {
         admin_User = TestDataFactory.createUser(true,'',SYSTEM_ADMINISTRATOR_PROFILE);
        
        insert admin_User;
        System.runAs(admin_User)
        {

            objectCloneSkippedFields= (Object_clone_skipped_field__mdt) TestDataFactory.operationOnObjectRecord(null, 'Object_clone_skipped_field__mdt', null);
            objectCloneSkippedFields.put('Parent_Object_Name__c','Product_Specification__c');
            objectCloneSkippedFields.put('Object_Name__c','State_Availability__c');
            objectCloneSkippedFields.put('Field_Name__c','Name');
            
        } 
    }
	private static testMethod void testGetChildSkipListByParentName() {
        testData();
        
        Test.startTest();
        Map<String,Set<String>> mapObjectClone = DAL_ObjectCloneSkippedField.getChildSkipListByParentName('Product_Specification__c');
        System.assert(mapObjectClone!=null);
        Test.stopTest();
	}

}