F&GDEV/src/objects/Product_Specification__c.object
<CustomObject>
    <description>Object utilized for Product Development efforts</description>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

F&GDEV/src/objects/State__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List of supported policy states.</description>
    <fields>
        <fullName>StateCode__c</fullName>
        <description>USPS 2 Character State Code</description>
        <externalId>true</externalId>
        <label>State Code</label>
        <length>2</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>State</label>
</CustomObject>

F&GDEV/src/objects/State_Availability__c.object
<CustomObject>
    <description>Object utilized for Product Development efforts</description>
    <fields>
        <fullName>Product_Specification__c</fullName>
        <label>Product Specification</label>
        <referenceTo>Product_Specification__c</referenceTo>
        <relationshipName>Product_State_Availabilities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>NC</fullName>
                </value>
                <value>
                    <fullName>ND</fullName>
                </value>
                <value>
                    <fullName>NE</fullName>
                </value>
                <value>
                    <fullName>NH</fullName>
                </value>
                <value>
                    <fullName>NJ</fullName>
                </value>
                <value>
                    <fullName>NM</fullName>
                </value>
                <value>
                    <fullName>NV</fullName>
                </value>
                <value>
                    <fullName>NY</fullName>
                </value>
                <value>
                    <fullName>OH</fullName>
                </value>
                <value>
                    <fullName>OK</fullName>
                </value>
                <value>
                    <fullName>OR</fullName>
                </value>
                <value>
                    <fullName>PA</fullName>
                </value>
                <value>
                    <fullName>RI</fullName>
                </value>
                <value>
                    <fullName>SC</fullName>
                </value>
                <value>
                    <fullName>SD</fullName>
                </value>
                <value>
                    <fullName>TN</fullName>
                </value>
                <value>
                    <fullName>TX</fullName>
                </value>
                <value>
                    <fullName>UT</fullName>
                </value>
                <value>
                    <fullName>VA</fullName>
                </value>
                <value>
                    <fullName>VT</fullName>
                </value>
                <value>
                    <fullName>WA</fullName>
                </value>
                <value>
                    <fullName>WI</fullName>
                </value>
                <value>
                    <fullName>WV</fullName>
                </value>
                <value>
                    <fullName>WY</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Product State</label>
    <nameField>
        <label>Product State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product States</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

F&GDEV/src/classes/ProductStateHandlerTest.cls
@isTest
public class ProductStateHandlerTest {
	@isTest static void CreateProductState() {
		initStateRecs();

		// Batch Create Product Specs
		List<Product_Specification__c> prodspecList = (List<Product_Specification__c>)SmartFactory.createSObjectList('Product_Specification__c', false, 10);
		Integer i = 0;
		for(Product_Specification__c prodspec : prodspecList){
			prodspec.Name = 'Prod Spec Name ' + i;
			i += 1;
		}
		insert prodspecList;

		//	Create a Map of Product Specs
		Map<Id, Product_Specification__c> prodspecMap = new Map<Id, Product_Specification__c>([Select Id, Name from Product_Specification__c]);

		//	Validate Names of State Availability Records
		for(State_Availability__c stateavail : [Select Name, Product_Specification__c, State__c from State_Availability__c]){
			System.assertEquals(prodspecMap.get(stateavail.Product_Specification__c).Name + ' - ' + stateavail.State__c, stateavail.Name);
		}
	}
	
	private static void initStateRecs(){
		List<State__c> stateavailList = new List<State__c>();
		stateavailList.add(new State__c(Name='Alaska',StateCode__c = 'AK'));
		stateavailList.add(new State__c(Name='Alabama',StateCode__c = 'AL'));
		stateavailList.add(new State__c(Name='Arkansas',StateCode__c = 'AR'));
		stateavailList.add(new State__c(Name='Arizona',StateCode__c = 'AZ'));
		stateavailList.add(new State__c(Name='California',StateCode__c = 'CA'));
		stateavailList.add(new State__c(Name='Colorado',StateCode__c = 'CO'));
		stateavailList.add(new State__c(Name='Connecticut',StateCode__c = 'CT'));
		stateavailList.add(new State__c(Name='District of Columbia',StateCode__c = 'DC'));
		stateavailList.add(new State__c(Name='Delaware',StateCode__c = 'DE'));
		stateavailList.add(new State__c(Name='Florida',StateCode__c = 'FL'));
		stateavailList.add(new State__c(Name='Georgia',StateCode__c = 'GA'));
		stateavailList.add(new State__c(Name='Hawaii',StateCode__c = 'HI'));
		stateavailList.add(new State__c(Name='Iowa',StateCode__c = 'IA'));
		stateavailList.add(new State__c(Name='Idaho',StateCode__c = 'ID'));
		stateavailList.add(new State__c(Name='Illinois',StateCode__c = 'IL'));
		stateavailList.add(new State__c(Name='Indiana',StateCode__c = 'IN'));
		stateavailList.add(new State__c(Name='Kansas',StateCode__c = 'KS'));
		stateavailList.add(new State__c(Name='Kentucky',StateCode__c = 'KY'));
		stateavailList.add(new State__c(Name='Louisiana',StateCode__c = 'LA'));
		stateavailList.add(new State__c(Name='Massachusetts',StateCode__c = 'MA'));
		stateavailList.add(new State__c(Name='Maryland',StateCode__c = 'MD'));
		stateavailList.add(new State__c(Name='Maine',StateCode__c = 'ME'));
		stateavailList.add(new State__c(Name='Michigan',StateCode__c = 'MI'));
		stateavailList.add(new State__c(Name='Minnesota',StateCode__c = 'MN'));
		stateavailList.add(new State__c(Name='Missouri',StateCode__c = 'MO'));
		stateavailList.add(new State__c(Name='Mississippi',StateCode__c = 'MS'));
		stateavailList.add(new State__c(Name='Montana',StateCode__c = 'MT'));
		stateavailList.add(new State__c(Name='North Carolina',StateCode__c = 'NC'));
		stateavailList.add(new State__c(Name='North Dakota',StateCode__c = 'ND'));
		stateavailList.add(new State__c(Name='Nebraska',StateCode__c = 'NE'));
		stateavailList.add(new State__c(Name='New Hampshire',StateCode__c = 'NH'));
		stateavailList.add(new State__c(Name='New Jersey',StateCode__c = 'NJ'));
		stateavailList.add(new State__c(Name='New Mexico',StateCode__c = 'NM'));
		stateavailList.add(new State__c(Name='Nevada',StateCode__c = 'NV'));
		stateavailList.add(new State__c(Name='New York',StateCode__c = 'NY'));
		stateavailList.add(new State__c(Name='Ohio',StateCode__c = 'OH'));
		stateavailList.add(new State__c(Name='Oklahoma',StateCode__c = 'OK'));
		stateavailList.add(new State__c(Name='Oregon',StateCode__c = 'OR'));
		stateavailList.add(new State__c(Name='Pennsylvania',StateCode__c = 'PA'));
		stateavailList.add(new State__c(Name='Rhode Island',StateCode__c = 'RI'));
		stateavailList.add(new State__c(Name='South Carolina',StateCode__c = 'SC'));
		stateavailList.add(new State__c(Name='South Dakota',StateCode__c = 'SD'));
		stateavailList.add(new State__c(Name='Tennessee',StateCode__c = 'TN'));
		stateavailList.add(new State__c(Name='Texas',StateCode__c = 'TX'));
		stateavailList.add(new State__c(Name='Utah',StateCode__c = 'UT'));
		stateavailList.add(new State__c(Name='Virginia',StateCode__c = 'VA'));
		stateavailList.add(new State__c(Name='Vermont',StateCode__c = 'VT'));
		stateavailList.add(new State__c(Name='Washington',StateCode__c = 'WA'));
		stateavailList.add(new State__c(Name='Wisconsin',StateCode__c = 'WI'));
		stateavailList.add(new State__c(Name='West Virginia',StateCode__c = 'WV'));
		stateavailList.add(new State__c(Name='Wyoming',StateCode__c = 'WY'));


		insert stateavailList;
	}

}