F&GDEV/src/objects/Product_Specification__c.object
<CustomObject>
    <description>Object utilized for Product Development efforts</description>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

F&GDEV/src/objects/State__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List of supported policy states.</description>
    <fields>
        <fullName>StateCode__c</fullName>
        <description>USPS 2 Character State Code</description>
        <externalId>true</externalId>
        <label>State Code</label>
        <length>2</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>excludeFromProductStateCreation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>excludeFromProductStateCreation</label>
        <type>Checkbox</type>
    </fields>
    <label>State</label>
</CustomObject>

F&GDEV/src/objects/State_Availability__c.object
<CustomObject>
    <description>Object utilized for Product Development efforts</description>
    <fields>
        <fullName>Product_Specification__c</fullName>
        <label>Product Specification</label>
        <referenceTo>Product_Specification__c</referenceTo>
        <relationshipName>Product_State_Availabilities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>NC</fullName>
                </value>
                <value>
                    <fullName>ND</fullName>
                </value>
                <value>
                    <fullName>NE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TranscationId__c</fullName>
        <formula>CASESAFEID(Product_Specification__r.Id )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>TranscationId</label>
        <type>Text</type>
    </fields>
    <label>Product State</label>
    <nameField>
        <label>Product State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product States</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

F&GDEV/src/classes/ProductSpecificationHandler.cls
public with sharing class ProductSpecificationHandler  extends BaseTriggerHandler {
	
	
	private List<Product_Specification__c> newProduct_Specification;
    private List<Product_Specification__c> oldProduct_Specifications;
    private Map<ID, Product_Specification__c> newProduct_SpecificationMap;
    private Map<ID, Product_Specification__c> oldProduct_SpecificationlMap;
	
	public ProductSpecificationHandler()
    {
        oldProduct_Specifications = (List<Product_Specification__c>)Trigger.old;
        newProduct_Specification = (List<Product_Specification__c>)Trigger.new;
        newProduct_SpecificationMap = (Map<ID, Product_Specification__c>)Trigger.newMap;
        oldProduct_SpecificationlMap = (Map<ID, Product_Specification__c>)Trigger.oldMap;
    }
    
    
     @TestVisible
    protected override void afterInsert()
    {
    	if(TriggerCheck.canRun('TH_PRODUCTSPECIFICATIONHANDLER'))
        {
    		createStateAvailRecs(trigger.isAfter, trigger.isInsert, newProduct_SpecificationMap);
        }
    }
    
    
    @TestVisible
    protected override void afterUpdate()
    {
		if(TriggerCheck.canRun('TH_PRODUCTSPECIFICATIONHANDLER'))
		{
			updateStateAvailRecs(trigger.isAfter,newProduct_Specification,oldProduct_SpecificationlMap,newProduct_SpecificationMap);
		}
    }
    
    public  void createStateAvailRecs(Boolean isAfter, Boolean isInsert, Map<Id, Product_Specification__c> newmap){
        if(isAfter && isInsert){
            List<State_Availability__c> stateavailList = new List<State_Availability__c>();

            for(State__c state : State__c.getAll().values())
            {
               if(!state.excludeFromProductStateCreation__c)
               {
	                //  Loop All Product Spec Records and Create a State Avail Record for Every Spec Record for Every State
	                for(Id prodid : newmap.keySet())
	                {
	                    stateavailList.add(new State_Availability__c(Product_Specification__c = prodid, State__c = state.StateCode__c));
	                }
               }
            }

            //  Insert State Availability if the Recs Exist
            if(stateavailList.size() > 0){
                insert stateavailList;
            }
        }

    }
    
    
     public static void updateStateAvailRecs(Boolean isAfter,List<Product_Specification__c> newProductSpecfication,
     										 Map<Id, Product_Specification__c> oldmap, 
     										 Map<Id, Product_Specification__c> newMap)
     {
        if(isAfter)
        {
        	List<Id> idsforWhichNameChanged = new List<Id>();
        	for(Product_Specification__c ps: newProductSpecfication)
        	{
        		if(oldmap.get(ps.Id).Name != ps.Name)
        		{
        			idsforWhichNameChanged.add(ps.Id);
        		}
        	}
        	
        	
        	if(! idsforWhichNameChanged.isEmpty())
        	{
            	Map<Id,List<State_Availability__c>> byTranxcationIdMap = DAL_StateAvailability.getByTranxcationIdMap(idsforWhichNameChanged);
            	List<State_Availability__c> toUpdateState_Availability = new List<State_Availability__c>();
                for(Id i: idsforWhichNameChanged)
                {
                    for(State_Availability__c s: byTranxcationIdMap.get(i))
                    {
                        toUpdateState_Availability.add(new State_Availability__c(Id=s.Id,
                                                                                 Name = newMap.get(s.TranscationId__c).Name+'-'+s.State__c));
                    }
                }
            	
            	if(!toUpdateState_Availability.isEmpty())
            	{
            		update toUpdateState_Availability;
            	}
        	}
        	
        }

    }
}