F&GDEV/src/objects/Product_Specification__c.object
<CustomObject>
    <description>Object utilized for Product Development efforts</description>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

F&GDEV/src/objects/State__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List of supported policy states.</description>
    <label>State</label>
</CustomObject>

F&GDEV/src/objects/State_Availability__c.object
<CustomObject>
    <description>Object utilized for Product Development efforts</description>
    <fields>
        <fullName>Product_Specification__c</fullName>
        <label>Product Specification</label>
        <referenceTo>Product_Specification__c</referenceTo>
        <relationshipName>Product_State_Availabilities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>NC</fullName>
                </value>
                <value>
                    <fullName>ND</fullName>
                </value>
                <value>
                    <fullName>NE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Product State</label>
    <nameField>
        <label>Product State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product States</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

F&GDEV/src/classes/ProductStateHandler.cls
public with sharing class ProductStateHandler extends BaseTriggerHandler {
	
	
	private List<State_Availability__c> newStateAvailability;
    private List<State_Availability__c> oldStateAvailabilitys;
    private Map<ID, State_Availability__c> newStateAvailabilityMap;
    private Map<ID, State_Availability__c> oldStateAvailabilitylMap;
	
	public ProductStateHandler()
    {
        oldStateAvailabilitys = (List<State_Availability__c>)Trigger.old;
        newStateAvailability = (List<State_Availability__c>)Trigger.new;
        newStateAvailabilityMap = (Map<ID, State_Availability__c>)Trigger.newMap;
        oldStateAvailabilitylMap = (Map<ID, State_Availability__c>)Trigger.oldMap;
    }
    
    
     @TestVisible
    protected override void beforeInsert()
    {
    	if(TriggerCheck.canRun('TH_PRODUCTSTATEHANDLER'))
        {
    		nameProductStateRecord(Trigger.isBefore, Trigger.isInsert, newStateAvailability);
        }
    }
    
	public void nameProductStateRecord(Boolean isBefore, Boolean isInsert, List<State_Availability__c> newList) {
		if(isBefore && isInsert){
			//	Retrieve List of Product Names

			//	-- Create Set of Product Spec Ids
			Set<Id> ProductIdSet = new Set<Id>();
			for(State_Availability__c prodstate : newList){
				ProductIdSet.add(prodstate.Product_Specification__c);
			}

			//	-- Create Map of Product Spec Id to Product Name
			Map<Id, Product_Specification__c> prodspecMap = new Map<Id, Product_Specification__c>([Select Id, Name from Product_Specification__c Where Id in:ProductIdSet]);

			for(State_Availability__c prodstate : newList){
				if(prodspecMap.containsKey(prodstate.Product_Specification__c)){
					prodstate.Name = prodspecMap.get(prodstate.Product_Specification__c).Name + ' - ' + prodstate.State__c;
				}
			}
		}
	}
}