F&GDEV/src/objects/State__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List of supported policy states.</description>
    <label>State</label>
</CustomObject>

F&GDEV/src/objects/State_Availability__c.object
<CustomObject>
    <description>Object utilized for Product Development efforts</description>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>NC</fullName>
                </value>
                <value>
                    <fullName>ND</fullName>
                </value>
                <value>
                    <fullName>NE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TranscationId__c</fullName>
        <formula>CASESAFEID(Product_Specification__r.Id )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>TranscationId</label>
        <type>Text</type>
    </fields>
    <label>Product State</label>
    <nameField>
        <label>Product State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product States</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

F&GDEV/src/classes/DAL_StateAvailability.cls
public class DAL_StateAvailability {
    
    public static List<State_Availability__c> getByTranxcationId(String tranxId)
    {
        return [SELECT
                       Id
                   FROM
                       State_Availability__c
                  WHERE 
                       TranscationId__c =:tranxId];
    }
    
    public static Map<Id,List<State_Availability__c>> getByTranxcationIdMap(List<Id> tranxIds)
    {
        List<State_Availability__c> stateAvailabiltys = [SELECT
										                       Id,
										                       TranscationId__c,
										                       Name,
										                       State__c
										                   FROM
										                       State_Availability__c
										                  WHERE 
										                       TranscationId__c IN:tranxIds];
										                       
		Map<Id,List<State_Availability__c>>	tranxcationIdMap = new Map<Id,List<State_Availability__c>>();	
		for(State_Availability__c stateAvailabilty: stateAvailabiltys)
		{
			List<State_Availability__c> stateAvailabiltyss  = null;
			{
				if(tranxcationIdMap.get(stateAvailabilty.TranscationId__c) != null)
				{
					stateAvailabiltyss  = tranxcationIdMap.get(stateAvailabilty.TranscationId__c);
				}else
				{
					stateAvailabiltyss  = new List<State_Availability__c>();
				}
		        stateAvailabiltyss.add(stateAvailabilty);
			}
			tranxcationIdMap.put(stateAvailabilty.TranscationId__c,stateAvailabiltyss);
		}
		
		return tranxcationIdMap;			                       
    }
    
}