F&GDEV/src/objects/State_Availability__c.object
<CustomObject>
    <description>Object utilized for Product Development efforts</description>
    <fields>
        <fullName>Approval_Date__c</fullName>
        <label>Approval Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Launch_Date__c</fullName>
        <label>Launch Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Pull_Date__c</fullName>
        <label>Pull Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>NBS</fullName>
                </value>
                <value>
                    <fullName>Filing Targeted</fullName>
                </value>
                <value>
                    <fullName>Filed, Objection Pending</fullName>
                </value>
                <value>
                    <fullName>Filing Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Publishing</fullName>
                </value>
                <value>
                    <fullName>Launched</fullName>
                </value>
                <value>
                    <fullName>Pulled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Target_Launch_Date__c</fullName>
        <label>Target Launch Date</label>
        <type>Date</type>
    </fields>
    <label>Product State</label>
    <nameField>
        <label>Product State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product States</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

F&GDEV/src/classes/W_ProdStateAvail.cls
global with sharing class W_ProdStateAvail
{
	global W_ProdStateAvail(State_Availability__c stateavail) {
		this.StateAvailId = stateavail.Id;
		this.PolicytoProdStateStat = new Map<Id, W_ProdStateStatus>();	
	}
    global W_ProdStateAvail(State_Availability__c stateavail,String ltng) {
		this.StateAvailId = stateavail.Id;
        this.Status = stateavail.Status__c;
        if(!string.isBlank(stateavail.Status__c)){
            if(stateavail.Status__c=='Approved'){
                this.StatusDate = stateavail.Approval_Date__c;
            }else if(stateavail.Status__c=='Filing Targeted'){
                this.StatusDate = stateavail.Target_Launch_Date__c;
            }else if(stateavail.Status__c=='Launched'){
                this.StatusDate = stateavail.Launch_Date__c;
            }else if(stateavail.Status__c=='Pulled'){
                this.StatusDate = stateavail.Pull_Date__c;
            }
        }
		this.PolicytoProdStateStat = new Map<Id, W_ProdStateStatus>();	
	}

	global Id StateAvailId{get; set;}
	global Map<Id, W_ProdStateStatus> PolicytoProdStateStat	{get; set;}
    global String Status{get; set;}
    global Date StatusDate{get; set;}
}