F&GDEV/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>ByPassTrigger__c</fullName>
        <label>By pass trigger</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>TH_MARKETINGMATERIALSHANDLER</fullName>
                </value>
                <value>
                    <fullName>TH_POLICYSTATEHANDLER</fullName>
                </value>
                <value>
                    <fullName>TH_PRODUCTSTATEPOLICYASSOCHANDLER</fullName>
                </value>
                <value>
                    <fullName>TH_PRODUCTSPECIFICATIONHANDLER</fullName>
                </value>
                <value>
                    <fullName>TH_PRODUCTSTATEHANDLER</fullName>
                </value>
                <value>
                    <fullName>TH_PROJECTHANDLER</fullName>
                </value>
                <value>
                    <fullName>TH_POLICYFORMDETAILHANDLER</fullName>
                </value>
                <value>
                    <fullName>TH_APPROVALSTATE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ByPassValidation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>By Pass Validation</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

F&GDEV/src/classes/TriggerCheck_T.cls
@isTest
private  class TriggerCheck_T {
   
    @isTest
    private static void test() {
        
        Profile p = [select id from profile where name='Utilisateur Standard' OR name='Standard User' LIMIT 1]; 
        
        User u = new User(alias = 'standt', email='standarduser@testorg.com',emailencodingkey='UTF-8', 
                          lastname='Testing', languagelocalekey='en_US', localesidkey='en_US', 
                          profileid = p.Id, timezonesidkey='America/Los_Angeles', 
                          username='standarduser@seb.com', 
                          ByPassTrigger__c  ='TR01;TR02',
                          ByPassValidation__c  =true);
                          
          insert u;                
         
        System.runAs(u) {
            System.assert(TriggerCheck.canRun('TR01') == false);
            System.assert(TriggerCheck.canRun('TR03') == true);
            
            TriggerCheck.deactivateTrigger('TR03');
            System.assert(TriggerCheck.canRun('TR03') == false);
            
            TriggerCheck.activateTrigger('TR01');
            System.assert(TriggerCheck.canRun('TR01') == true);          
         }
    }
}